-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\Luiz\Documents\GitHub\Advanced-Digital-System-Development-Using-MATLAB-C-and-VHDL\1_HDL_AND_VHDL_LANGUAGES\3_EXAMPLE_FIR_FILTER_HDL_CODER\codegen\hdl_IP\hdlsrc\dsphdl_FIRFilter.vhd
-- Created: 2026-02-02 18:58:55
-- 
-- Generated by MATLAB 25.2, MATLAB Coder 25.2 and HDL Coder 25.2
-- 
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: dsphdl_FIRFilter
-- Source Path: hdl_IP/dsphdl.FIRFilter
-- Hierarchy Level: 1
-- 
-- Discrete FIR Filter
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY dsphdl_FIRFilter IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dataIn                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        validIn                           :   IN    std_logic;
        dataOut                           :   OUT   std_logic_vector(32 DOWNTO 0);  -- sfix33_En32
        validOut                          :   OUT   std_logic
        );
END dsphdl_FIRFilter;


ARCHITECTURE rtl OF dsphdl_FIRFilter IS

  -- Component Declarations
  COMPONENT Filter
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          validIn                         :   IN    std_logic;
          syncReset                       :   IN    std_logic;
          dataOut                         :   OUT   std_logic_vector(32 DOWNTO 0);  -- sfix33_En32
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Filter
    USE ENTITY work.Filter(rtl);

  -- Signals
  SIGNAL syncReset                        : std_logic;
  SIGNAL dataOut_tmp                      : std_logic_vector(32 DOWNTO 0);  -- ufix33

BEGIN
  u_FilterBank : Filter
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => dataIn,  -- sfix16_En15
              validIn => validIn,
              syncReset => syncReset,
              dataOut => dataOut_tmp,  -- sfix33_En32
              validOut => validOut
              );

  syncReset <= '0';

  dataOut <= dataOut_tmp;

END rtl;

