-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\Luiz\Documents\GitHub\Advanced-Digital-System-Development-Using-MATLAB-C-and-VHDL\1_HDL_AND_VHDL_LANGUAGES\3_EXAMPLE_FIR_FILTER_HDL_CODER\codegen\hdl_IP\hdlsrc\FilterCoef.vhd
-- Created: 2026-02-02 18:58:55
-- 
-- Generated by MATLAB 25.2, MATLAB Coder 25.2 and HDL Coder 25.2
-- 
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: FilterCoef
-- Source Path: hdl_IP/dsphdl.FIRFilter/Filter/FilterCoef
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.hdl_IP_pkg.ALL;

ENTITY FilterCoef IS
  PORT( validIn                           :   IN    std_logic;
        syncReset                         :   IN    std_logic;
        CoefOut                           :   OUT   vector_of_std_logic_vector16(0 TO 5)  -- sfix16_En17 [6]
        );
END FilterCoef;


ARCHITECTURE rtl OF FilterCoef IS

  -- Signals
  SIGNAL CoefData                         : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_1                       : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_2                       : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_3                       : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_4                       : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefData_5                       : signed(15 DOWNTO 0);  -- sfix16_En17
  SIGNAL CoefOut_tmp                      : vector_of_signed16(0 TO 5);  -- sfix16_En17 [6]

BEGIN
  -- CoefReg_1
  CoefData <= to_signed(16#4F52#, 16);

  -- CoefReg_2
  CoefData_1 <= to_signed(16#5676#, 16);

  -- CoefReg_3
  CoefData_2 <= to_signed(16#5A37#, 16);

  -- CoefReg_4
  CoefData_3 <= to_signed(16#5A37#, 16);

  -- CoefReg_5
  CoefData_4 <= to_signed(16#5676#, 16);

  -- CoefReg_6
  CoefData_5 <= to_signed(16#4F52#, 16);

  CoefOut_tmp(0) <= CoefData;
  CoefOut_tmp(1) <= CoefData_1;
  CoefOut_tmp(2) <= CoefData_2;
  CoefOut_tmp(3) <= CoefData_3;
  CoefOut_tmp(4) <= CoefData_4;
  CoefOut_tmp(5) <= CoefData_5;

  outputgen: FOR k IN 0 TO 5 GENERATE
    CoefOut(k) <= std_logic_vector(CoefOut_tmp(k));
  END GENERATE;

END rtl;

