-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\Luiz\Documents\GitHub\Advanced-Digital-System-Development-Using-MATLAB-C-and-VHDL\1_HDL_AND_VHDL_LANGUAGES\3_EXAMPLE_FIR_FILTER_HDL_CODER\codegen\hdl_IP\hdlsrc\Filter.vhd
-- Created: 2026-02-02 18:58:55
-- 
-- Generated by MATLAB 25.2, MATLAB Coder 25.2 and HDL Coder 25.2
-- 
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Filter
-- Source Path: hdl_IP/dsphdl.FIRFilter/Filter
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.hdl_IP_pkg.ALL;

ENTITY Filter IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dataIn                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        validIn                           :   IN    std_logic;
        syncReset                         :   IN    std_logic;
        dataOut                           :   OUT   std_logic_vector(32 DOWNTO 0);  -- sfix33_En32
        validOut                          :   OUT   std_logic
        );
END Filter;


ARCHITECTURE rtl OF Filter IS

  -- Component Declarations
  COMPONENT FilterCoef
    PORT( validIn                         :   IN    std_logic;
          syncReset                       :   IN    std_logic;
          CoefOut                         :   OUT   vector_of_std_logic_vector16(0 TO 5)  -- sfix16_En17 [6]
          );
  END COMPONENT;

  COMPONENT subFilter
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dinReg2_0_re                    :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          coefIn                          :   IN    vector_of_std_logic_vector16(0 TO 5);  -- sfix16_En17 [6]
          dinRegVld                       :   IN    std_logic;
          syncReset                       :   IN    std_logic;
          dout_1_re                       :   OUT   std_logic_vector(32 DOWNTO 0);  -- sfix33_En32
          doutVld                         :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : FilterCoef
    USE ENTITY work.FilterCoef(rtl);

  FOR ALL : subFilter
    USE ENTITY work.subFilter(rtl);

  -- Signals
  SIGNAL dinRegVld                        : std_logic;
  SIGNAL dataIn_signed                    : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL dinReg_0_re                      : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL dinReg2_0_re                     : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL CoefOut                          : vector_of_std_logic_vector16(0 TO 5);  -- ufix16 [6]
  SIGNAL dinReg2Vld                       : std_logic;
  SIGNAL dout_1_re                        : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL doutVld                          : std_logic;

BEGIN
  u_CoefTable_1 : FilterCoef
    PORT MAP( validIn => validIn,
              syncReset => syncReset,
              CoefOut => CoefOut  -- sfix16_En17 [6]
              );

  u_subFilter_1_re : subFilter
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dinReg2_0_re => std_logic_vector(dinReg2_0_re),  -- sfix16_En15
              coefIn => CoefOut,  -- sfix16_En17 [6]
              dinRegVld => dinReg2Vld,
              syncReset => syncReset,
              dout_1_re => dout_1_re,  -- sfix33_En32
              doutVld => doutVld
              );

  intdelay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        dinRegVld <= '0';
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          dinRegVld <= '0';
        ELSE 
          dinRegVld <= validIn;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_process;


  dataIn_signed <= signed(dataIn);

  intdelay_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        dinReg_0_re <= to_signed(16#0000#, 16);
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          dinReg_0_re <= to_signed(16#0000#, 16);
        ELSIF validIn = '1' THEN
          dinReg_0_re <= dataIn_signed;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_1_process;


  intdelay_2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        dinReg2_0_re <= to_signed(16#0000#, 16);
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          dinReg2_0_re <= to_signed(16#0000#, 16);
        ELSIF dinRegVld = '1' THEN
          dinReg2_0_re <= dinReg_0_re;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_2_process;


  intdelay_3_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        dinReg2Vld <= '0';
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          dinReg2Vld <= '0';
        ELSE 
          dinReg2Vld <= dinRegVld;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_3_process;


  dataOut <= dout_1_re;

  validOut <= doutVld;

END rtl;

