-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\Luiz\Documents\GitHub\Advanced-Digital-System-Development-Using-MATLAB-C-and-VHDL\1_HDL_AND_VHDL_LANGUAGES\3_EXAMPLE_FIR_FILTER_HDL_CODER\codegen\hdl_IP\hdlsrc\hdl_IP.vhd
-- Created: 2026-02-02 18:58:55
-- 
-- Generated by MATLAB 25.2, MATLAB Coder 25.2 and HDL Coder 25.2
-- 
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Design base rate: 1
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- dataOut                       ce_out        1
-- validOut                      ce_out        1
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: hdl_IP
-- Source Path: hdl_IP
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY hdl_IP IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        dataIn                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        validIn                           :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        dataOut                           :   OUT   std_logic_vector(32 DOWNTO 0);  -- sfix33_En32
        validOut                          :   OUT   std_logic
        );
END hdl_IP;


ARCHITECTURE rtl OF hdl_IP IS

  -- Component Declarations
  COMPONENT dsphdl_FIRFilter
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          validIn                         :   IN    std_logic;
          dataOut                         :   OUT   std_logic_vector(32 DOWNTO 0);  -- sfix33_En32
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : dsphdl_FIRFilter
    USE ENTITY work.dsphdl_FIRFilter(rtl);

  -- Signals
  SIGNAL varargout_1                      : std_logic_vector(32 DOWNTO 0);  -- ufix33
  SIGNAL varargout_2                      : std_logic;

BEGIN
  -- Generated by HDL IP Designer.
  u_dsphdl_FIRFilter : dsphdl_FIRFilter
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              dataIn => dataIn,  -- sfix16_En15
              validIn => validIn,
              dataOut => varargout_1,  -- sfix33_En32
              validOut => varargout_2
              );

  ce_out <= clk_enable;

  dataOut <= varargout_1;

  validOut <= varargout_2;

END rtl;

