-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\Luiz\Documents\GitHub\Advanced-Digital-System-Development-Using-MATLAB-C-and-VHDL\1_HDL_AND_VHDL_LANGUAGES\3_EXAMPLE_FIR_FILTER_HDL_CODER\codegen\hdl_IP\hdlsrc\subFilter.vhd
-- Created: 2026-02-02 18:58:55
-- 
-- Generated by MATLAB 25.2, MATLAB Coder 25.2 and HDL Coder 25.2
-- 
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: subFilter
-- Source Path: hdl_IP/dsphdl.FIRFilter/Filter/subFilter
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.hdl_IP_pkg.ALL;

ENTITY subFilter IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dinReg2_0_re                      :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        coefIn                            :   IN    vector_of_std_logic_vector16(0 TO 5);  -- sfix16_En17 [6]
        dinRegVld                         :   IN    std_logic;
        syncReset                         :   IN    std_logic;
        dout_1_re                         :   OUT   std_logic_vector(32 DOWNTO 0);  -- sfix33_En32
        doutVld                           :   OUT   std_logic
        );
END subFilter;


ARCHITECTURE rtl OF subFilter IS

  -- Component Declarations
  COMPONENT FilterTapSystolicPreAddWvlIn
    PORT( clk                             :   IN    std_logic;
          enb                             :   IN    std_logic;
          dinReg2_0_re                    :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          dinPreAdd                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          coefIn_0                        :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En17
          addin                           :   IN    std_logic_vector(47 DOWNTO 0);  -- sfix48_En32
          dinRegVld                       :   IN    std_logic;
          syncReset                       :   IN    std_logic;
          dinDly2                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          tapout                          :   OUT   std_logic_vector(47 DOWNTO 0)  -- sfix48_En32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : FilterTapSystolicPreAddWvlIn
    USE ENTITY work.FilterTapSystolicPreAddWvlIn(rtl);

  -- Signals
  SIGNAL intdelay_reg                     : std_logic_vector(6 DOWNTO 0);  -- ufix1 [7]
  SIGNAL vldShift                         : std_logic;
  SIGNAL vldOutTmp                        : std_logic;
  SIGNAL ZERO_OUT                         : signed(32 DOWNTO 0);  -- sfix33_En32
  SIGNAL addin                            : signed(47 DOWNTO 0);  -- sfix48_En32
  SIGNAL dinDly2                          : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL dinDly2_1                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout                           : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL dinDly2_2                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL tapout_1                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL tapout_2                         : std_logic_vector(47 DOWNTO 0);  -- ufix48
  SIGNAL tapout_signed                    : signed(47 DOWNTO 0);  -- sfix48_En32
  SIGNAL dout_cast                        : signed(32 DOWNTO 0);  -- sfix33_En32
  SIGNAL muxOut                           : signed(32 DOWNTO 0);  -- sfix33_En32
  SIGNAL dout_1_re_tmp                    : signed(32 DOWNTO 0);  -- sfix33_En32

BEGIN
  u_FilterTap_1 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinReg2_0_re,  -- sfix16_En15
              dinPreAdd => dinDly2,  -- sfix16_En15
              coefIn_0 => coefIn(0),  -- sfix16_En17
              addin => std_logic_vector(addin),  -- sfix48_En32
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_1,  -- sfix16_En15
              tapout => tapout  -- sfix48_En32
              );

  u_FilterTap_2 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_1,  -- sfix16_En15
              dinPreAdd => dinDly2,  -- sfix16_En15
              coefIn_0 => coefIn(1),  -- sfix16_En17
              addin => tapout,  -- sfix48_En32
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2_2,  -- sfix16_En15
              tapout => tapout_1  -- sfix48_En32
              );

  u_FilterTap_3 : FilterTapSystolicPreAddWvlIn
    PORT MAP( clk => clk,
              enb => enb,
              dinReg2_0_re => dinDly2_2,  -- sfix16_En15
              dinPreAdd => dinDly2,  -- sfix16_En15
              coefIn_0 => coefIn(2),  -- sfix16_En17
              addin => tapout_1,  -- sfix48_En32
              dinRegVld => dinRegVld,
              syncReset => syncReset,
              dinDly2 => dinDly2,  -- sfix16_En15
              tapout => tapout_2  -- sfix48_En32
              );

  intdelay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        intdelay_reg <= (OTHERS => '0');
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          intdelay_reg <= (OTHERS => '0');
        ELSIF dinRegVld = '1' THEN
          intdelay_reg(0) <= dinRegVld;
          intdelay_reg(6 DOWNTO 1) <= intdelay_reg(5 DOWNTO 0);
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_process;

  vldShift <= intdelay_reg(6);

  vldOutTmp <= dinRegVld AND vldShift;

  ZERO_OUT <= to_signed(0, 33);

  addin <= to_signed(0, 48);

  tapout_signed <= signed(tapout_2);

  dout_cast <= tapout_signed(32 DOWNTO 0);

  
  muxOut <= ZERO_OUT WHEN vldOutTmp = '0' ELSE
      dout_cast;

  intdelay_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        dout_1_re_tmp <= to_signed(0, 33);
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          dout_1_re_tmp <= to_signed(0, 33);
        ELSE 
          dout_1_re_tmp <= muxOut;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_1_process;


  dout_1_re <= std_logic_vector(dout_1_re_tmp);

  intdelay_2_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        doutVld <= '0';
      ELSIF enb = '1' THEN
        IF syncReset = '1' THEN
          doutVld <= '0';
        ELSE 
          doutVld <= vldOutTmp;
        END IF;
      END IF;
    END IF;
  END PROCESS intdelay_2_process;


END rtl;

