-- -------------------------------------------------------------
-- 
-- File Name: C:\curso_HDL_Vanderlei\Advanced-Digital-System-Development-Using-MATLAB-C-and-VHDL\1_LINGUAGENS_HDL_E_VHDL\6_EXEMPLO_FILTRO_FIR_HDL_CODER\hdlsrc\filter_low_pass_simulink\filter_lo_ip_src_Discrete_FIR_Filter1.vhd
-- Created: 2025-09-15 17:09:09
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: filter_lo_ip_src_Discrete_FIR_Filter1
-- Source Path: filter_low_pass_simulink/Discrete FIR Filter1
-- Hierarchy Level: 1
-- Model version: 1.13
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY filter_lo_ip_src_Discrete_FIR_Filter1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Discrete_FIR_Filter1_in           :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        Discrete_FIR_Filter1_out          :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
        );
END filter_lo_ip_src_Discrete_FIR_Filter1;


ARCHITECTURE rtl OF filter_lo_ip_src_Discrete_FIR_Filter1 IS

  -- Component Declarations
  COMPONENT filter_lo_ip_src_nfp_gain_pow2_single
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          nfp_in1                         :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          nfp_in2                         :   IN    std_logic;  -- ufix1
          nfp_in3                         :   IN    std_logic_vector(8 DOWNTO 0);  -- sfix9
          nfp_out                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
          );
  END COMPONENT;

  COMPONENT filter_lo_ip_src_nfp_add_single
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          nfp_in1                         :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          nfp_in2                         :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          nfp_out                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : filter_lo_ip_src_nfp_gain_pow2_single
    USE ENTITY work.filter_lo_ip_src_nfp_gain_pow2_single(rtl);

  FOR ALL : filter_lo_ip_src_nfp_add_single
    USE ENTITY work.filter_lo_ip_src_nfp_add_single(rtl);

  -- Signals
  SIGNAL pw2_sign_const                   : std_logic;  -- ufix1
  SIGNAL pw2_shift_const                  : signed(8 DOWNTO 0);  -- sfix9
  SIGNAL gain0                            : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL delay1                           : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL pw2_sign_const_1                 : std_logic;  -- ufix1
  SIGNAL pw2_shift_const_1                : signed(8 DOWNTO 0);  -- sfix9
  SIGNAL gain1                            : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_nfp_gain_pow2_single : filter_lo_ip_src_nfp_gain_pow2_single
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              nfp_in1 => Discrete_FIR_Filter1_in,  -- single
              nfp_in2 => pw2_sign_const,  -- ufix1
              nfp_in3 => std_logic_vector(pw2_shift_const),  -- sfix9
              nfp_out => gain0  -- single
              );

  u_nfp_gain_pow2_single_1 : filter_lo_ip_src_nfp_gain_pow2_single
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              nfp_in1 => delay1,  -- single
              nfp_in2 => pw2_sign_const_1,  -- ufix1
              nfp_in3 => std_logic_vector(pw2_shift_const_1),  -- sfix9
              nfp_out => gain1  -- single
              );

  u_nfp_add_comp : filter_lo_ip_src_nfp_add_single
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              nfp_in1 => gain0,  -- single
              nfp_in2 => gain1,  -- single
              nfp_out => Discrete_FIR_Filter1_out  -- single
              );

  pw2_sign_const <= '0';

  pw2_shift_const <= to_signed(-16#001#, 9);

  unit_delay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        delay1 <= X"00000000";
      ELSIF enb = '1' THEN
        delay1 <= Discrete_FIR_Filter1_in;
      END IF;
    END IF;
  END PROCESS unit_delay_process;


  pw2_sign_const_1 <= '0';

  pw2_shift_const_1 <= to_signed(-16#001#, 9);

END rtl;

