/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: doFilter.c
 *
 * MATLAB Coder version            : 25.1
 * C/C++ source code generated on  : 22-Jan-2026 22:38:08
 */

/* Include Files */
#include "doFilter.h"
#include "SOSFilter.h"
#include "SystemCore.h"
#include "doFilter_data.h"
#include "doFilter_initialize.h"
#include "doFilter_internal_types.h"

/* Variable Definitions */
static dsp_SOSFilter Hd;

/* Function Definitions */
/*
 * DOFILTER Filters input x and returns output y.
 *
 * Arguments    : const double x[1000]
 *                double y[1000]
 * Return Type  : void
 */
void doFilter(const double x[1000], double y[1000])
{
  if (!isInitialized_doFilter) {
    doFilter_initialize();
  }
  /*  MATLAB Code */
  /*  Generated by MATLAB(R) 25.1 and DSP System Toolbox 25.1. */
  /*  Generated on: 22-Jan-2026 21:45:08 */
  /*  To generate C/C++ code from this function use the codegen command. */
  /*  Type 'help codegen' for more information. */
  /*  Dentro do doFilter */
  SystemCore_step(&Hd, x, y);
}

/*
 * Arguments    : void
 * Return Type  : void
 */
void doFilter_init(void)
{
  /*  The following code was used to design the filter coefficients: */
  /*  */
  /*  Fstop = 2000;   % Stopband Frequency */
  /*  Fpass = 3000;   % Passband Frequency */
  /*  Astop = 80;     % Stopband Attenuation (dB) */
  /*  Apass = 1;      % Passband Ripple (dB) */
  /*  Fs    = 48000;  % Sampling Frequency */
  /*  */
  /*  h = fdesign.highpass('fst,fp,ast,ap', Fstop, Fpass, Astop, Apass, Fs); */
  /*  */
  /*  Hd = design(h, 'butter', ... */
  /*      'MatchExactly', 'stopband', ... */
  /*      'SystemObject', true); */
  SOSFilter_SOSFilter(&Hd);
}

/*
 * File trailer for doFilter.c
 *
 * [EOF]
 */
