function Hd = filtro
%FILTRO Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 25.1 and Signal Processing Toolbox 25.1.
% Generated on: 22-Jan-2026 19:06:24

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
Fs = 48000;  % Sampling Frequency

Fpass = 9600;        % Passband Frequency
Fstop = 10000;       % Stopband Frequency
Apass = 1;           % Passband Ripple (dB)
Astop = 80;          % Stopband Attenuation (dB)
match = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
