-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\Luiz\Documents\GitHub\Advanced-Digital-System-Development-Using-MATLAB-C-and-VHDL\3_REDES_NEURAIS_E_PINS\4_EXEMPLO_PINN_EM_HDL\codegen\pinn_predict_hdl\hdlsrc\pinn_predict_hdl_fixpt_tb.vhd
-- Created: 2026-02-01 17:08:43
-- 
-- Generated by MATLAB 25.1, MATLAB Coder 25.1 and HDL Coder 25.1
-- 
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1
-- Target subsystem base rate: 1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: pinn_predict_hdl_fixpt_tb
-- Source Path: 
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_textio.ALL;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
LIBRARY STD;
USE STD.textio.ALL;
LIBRARY work;
USE work.pinn_predict_hdl_fixpt_pkg.ALL;
USE work.pinn_predict_hdl_fixpt_tb_pkg.ALL;

ENTITY pinn_predict_hdl_fixpt_tb IS
END pinn_predict_hdl_fixpt_tb;


ARCHITECTURE rtl OF pinn_predict_hdl_fixpt_tb IS

  -- Component Declarations
  COMPONENT pinn_predict_hdl_fixpt
    PORT( x                               :   IN    std_logic_vector(6 DOWNTO 0);  -- ufix7
          y                               :   OUT   std_logic_vector(13 DOWNTO 0)  -- ufix14_En8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : pinn_predict_hdl_fixpt
    USE ENTITY work.pinn_predict_hdl_fixpt(rtl);

  -- Signals
  SIGNAL clk                              : std_logic;
  SIGNAL reset                            : std_logic;
  SIGNAL enb                              : std_logic;
  SIGNAL y_done                           : std_logic;  -- ufix1
  SIGNAL rdEnb                            : std_logic;
  SIGNAL y_done_enb                       : std_logic;  -- ufix1
  SIGNAL y_addr                           : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL y_active                         : std_logic;  -- ufix1
  SIGNAL snkDone                          : std_logic;
  SIGNAL snkDonen                         : std_logic;
  SIGNAL resetn                           : std_logic;
  SIGNAL tb_enb                           : std_logic;
  SIGNAL ce_out                           : std_logic;
  SIGNAL y_enb                            : std_logic;  -- ufix1
  SIGNAL y_lastAddr                       : std_logic;  -- ufix1
  SIGNAL x_addr                           : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL x_active                         : std_logic;  -- ufix1
  SIGNAL x_enb                            : std_logic;  -- ufix1
  SIGNAL x_addr_delay_1                   : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL rawData_x                        : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL holdData_x                       : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL x_offset                         : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL x_1                              : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL x_2                              : std_logic_vector(6 DOWNTO 0);  -- ufix7
  SIGNAL y_1                              : std_logic_vector(13 DOWNTO 0);  -- ufix14
  SIGNAL y_unsigned                       : unsigned(13 DOWNTO 0);  -- ufix14_En8
  SIGNAL y_addr_delay_1                   : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL y_expected                       : unsigned(13 DOWNTO 0);  -- ufix14_En8
  SIGNAL y_ref                            : unsigned(13 DOWNTO 0);  -- ufix14_En8
  SIGNAL y_testFailure                    : std_logic;  -- ufix1

BEGIN
  u_pinn_predict_hdl_fixpt : pinn_predict_hdl_fixpt
    PORT MAP( x => x_2,  -- ufix7
              y => y_1  -- ufix14_En8
              );

  y_done_enb <= y_done AND rdEnb;

  
  y_active <= '1' WHEN y_addr /= to_unsigned(16#64#, 7) ELSE
      '0';

  enb <= rdEnb AFTER 2 ns;

  snkDonen <=  NOT snkDone;

  clk_gen: PROCESS 
  BEGIN
    clk <= '1';
    WAIT FOR 5 ns;
    clk <= '0';
    WAIT FOR 5 ns;
    IF snkDone = '1' THEN
      clk <= '1';
      WAIT FOR 5 ns;
      clk <= '0';
      WAIT FOR 5 ns;
      WAIT;
    END IF;
  END PROCESS clk_gen;

  reset_gen: PROCESS 
  BEGIN
    reset <= '1';
    WAIT FOR 20 ns;
    WAIT UNTIL clk'event AND clk = '1';
    WAIT FOR 2 ns;
    reset <= '0';
    WAIT;
  END PROCESS reset_gen;

  resetn <=  NOT reset;

  tb_enb <= resetn AND snkDonen;

  
  rdEnb <= tb_enb WHEN snkDone = '0' ELSE
      '0';

  ce_out <= enb AND (rdEnb AND tb_enb);

  y_enb <= ce_out AND y_active;

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 100
  y_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      y_addr <= to_unsigned(16#00#, 7);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF y_enb = '1' THEN
        IF y_addr >= to_unsigned(16#64#, 7) THEN 
          y_addr <= to_unsigned(16#00#, 7);
        ELSE 
          y_addr <= y_addr + to_unsigned(16#01#, 7);
        END IF;
      END IF;
    END IF;
  END PROCESS y_process;


  
  y_lastAddr <= '1' WHEN y_addr >= to_unsigned(16#64#, 7) ELSE
      '0';

  y_done <= y_lastAddr AND resetn;

  -- Delay to allow last sim cycle to complete
  checkDone_1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      snkDone <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF y_done_enb = '1' THEN
        snkDone <= y_done;
      END IF;
    END IF;
  END PROCESS checkDone_1_process;

  
  x_active <= '1' WHEN x_addr /= to_unsigned(16#64#, 7) ELSE
      '0';

  x_enb <= x_active AND (rdEnb AND tb_enb);

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 100
  x_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      x_addr <= to_unsigned(16#00#, 7);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF x_enb = '1' THEN
        IF x_addr >= to_unsigned(16#64#, 7) THEN 
          x_addr <= to_unsigned(16#00#, 7);
        ELSE 
          x_addr <= x_addr + to_unsigned(16#01#, 7);
        END IF;
      END IF;
    END IF;
  END PROCESS x_process;


  x_addr_delay_1 <= x_addr AFTER 1 ns;

  -- Data source for x
  x_fileread: PROCESS (x_addr_delay_1, tb_enb, rdEnb)
    FILE fp: TEXT open READ_MODE is "x.dat";
    VARIABLE l: LINE;
    VARIABLE read_data: std_logic_vector(7 DOWNTO 0);

  BEGIN
    IF tb_enb /= '1' THEN
    ELSIF rdEnb = '1' AND NOT ENDFILE(fp) THEN
      READLINE(fp, l);
      HREAD(l, read_data);
    END IF;
    rawData_x <= unsigned(read_data(6 DOWNTO 0));
  END PROCESS x_fileread;

  -- holdData reg for x
  stimuli_x_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      holdData_x <= (OTHERS => 'X');
    ELSIF clk'event AND clk = '1' THEN
      holdData_x <= rawData_x;
    END IF;
  END PROCESS stimuli_x_process;

  stimuli_x_1: PROCESS (rawData_x, rdEnb)
  BEGIN
    IF rdEnb = '0' THEN
      x_offset <= holdData_x;
    ELSE
      x_offset <= rawData_x;
    END IF;
  END PROCESS stimuli_x_1;

  x_1 <= x_offset AFTER 2 ns;

  x_2 <= std_logic_vector(x_1);

  y_unsigned <= unsigned(y_1);

  y_addr_delay_1 <= y_addr AFTER 1 ns;

  -- Data source for y_expected
  y_expected_fileread: PROCESS (y_addr_delay_1, tb_enb, rdEnb)
    FILE fp: TEXT open READ_MODE is "y_expected.dat";
    VARIABLE l: LINE;
    VARIABLE read_data: std_logic_vector(15 DOWNTO 0);

  BEGIN
    IF tb_enb /= '1' THEN
    ELSIF rdEnb = '1' AND NOT ENDFILE(fp) THEN
      READLINE(fp, l);
      HREAD(l, read_data);
    END IF;
    y_expected <= unsigned(read_data(13 DOWNTO 0));
  END PROCESS y_expected_fileread;

  y_ref <= y_expected;

  y_unsigned_checker: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      y_testFailure <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' AND y_unsigned /= y_ref THEN
        y_testFailure <= '1';
        ASSERT FALSE
          REPORT "Error in y_unsigned: Expected " & to_hex(y_ref) & (" Actual " & to_hex(y_unsigned))
          SEVERITY ERROR;
      END IF;
    END IF;
  END PROCESS y_unsigned_checker;

  completed_msg: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF snkDone = '1' THEN
        IF y_testFailure = '0' THEN
          ASSERT FALSE
            REPORT "**************TEST COMPLETED (PASSED)**************"
            SEVERITY NOTE;
        ELSE
          ASSERT FALSE
            REPORT "**************TEST COMPLETED (FAILED)**************"
            SEVERITY NOTE;
        END IF;
      END IF;
    END IF;
  END PROCESS completed_msg;

END rtl;

