-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\Luiz\Documents\GitHub\Advanced-Digital-System-Development-Using-MATLAB-C-and-VHDL\3_REDES_NEURAIS_E_PINS\4_EXEMPLO_PINN_EM_HDL\codegen\pinn_predict_hdl\hdlsrc\pinn_predict_hdl_fixpt_pkg.vhd
-- Created: 2026-02-01 17:05:19
-- 
-- Generated by MATLAB 25.1, MATLAB Coder 25.1 and HDL Coder 25.1
-- 
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE pinn_predict_hdl_fixpt_pkg IS
  TYPE vector_of_signed14 IS ARRAY (NATURAL RANGE <>) OF signed(13 DOWNTO 0);
  TYPE vector_of_signed33 IS ARRAY (NATURAL RANGE <>) OF signed(32 DOWNTO 0);
  TYPE vector_of_signed23 IS ARRAY (NATURAL RANGE <>) OF signed(22 DOWNTO 0);
  TYPE vector_of_signed34 IS ARRAY (NATURAL RANGE <>) OF signed(33 DOWNTO 0);
END pinn_predict_hdl_fixpt_pkg;

