%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%          Generated by MATLAB 25.1 and Fixed-Point Designer 25.1          %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function y = pinn_predict_hdl_fixpt(x)
%#codegen
%PINN_PREDICT_HDL Wrapper para uso com HDL Coder (pesos numericos fixos).

fm = get_fimath();

persistent W1 b1 W2 b2 W3 b3 W4 b4
if isempty(W1)
    s1 = coder.load('pinn_weights.mat', 'W1','b1','W2','b2','W3','b3','W4','b4');
    s = copyTo_s(s1);
    W1 = fi(s.W1, 1, 14, 14, fm); b1 = fi(s.b1, 1, 14, 15, fm);
    W2 = fi(s.W2, 1, 14, 13, fm); b2 = fi(s.b2, 1, 14, 15, fm);
    W3 = fi(s.W3, 1, 14, 12, fm); b3 = fi(s.b3, 1, 14, 15, fm);
    W4 = fi(s.W4, 1, 14, 12, fm); b4 = fi(s.b4, 0, 14, 13, fm);
end

y = fi(pinn_forward_scalar(x, W1, b1, W2, b2, W3, b3, W4, b4), 0, 14, 8, fm);
end

function y = pinn_forward_scalar(x_1, W1, b1_1, W2, b2_1, W3, b3_1, W4, b4_1)
%#codegen
%PINN_FORWARD_SCALAR Forward pass com entrada escalar (amigavel a HDL).
% Arquitetura esperada: 1-32-32-32-1
% x: escalar

% Garante escalar
fm = get_fimath();
b1 = fi(b1_1, 1, 14, 15, fm);
b2 = fi(b2_1, 1, 14, 15, fm);
b3 = fi(b3_1, 1, 14, 15, fm);
b4 = fi(b4_1, 0, 14, 13, fm);
x = fi(x_1, 0, 7, 0, fm);

x = fi(x(1), 0, 7, 0, fm);

% Camada 1
b1 = fi(b1(:).', 1, 14, 15, fm);
a1 = fi(tanh(x * W1 + b1), 1, 14, 12, fm);

% Camada 2
b2 = fi(b2(:).', 1, 14, 15, fm);
a2 = fi(tanh(a1 * W2 + b2), 1, 14, 13, fm);

% Camada 3
b3 = fi(b3(:).', 1, 14, 15, fm);
a3 = fi(tanh(a2 * W3 + b3), 1, 14, 13, fm);

% Saida
b4 = fi(b4(:).', 0, 14, 13, fm);
y = fi(a3 * W4 + b4, 0, 14, 8, fm);
end


function s = copyTo_s(s1)
    coder.inline( 'always' );
    fm = get_fimath();
    s.W1 = fi( s1.W1, 1, 14, 14, fm );
    s.b1 = fi( s1.b1, 1, 14, 15, fm );
    s.W2 = fi( s1.W2, 1, 14, 13, fm );
    s.b2 = fi( s1.b2, 1, 14, 15, fm );
    s.W3 = fi( s1.W3, 1, 14, 12, fm );
    s.b3 = fi( s1.b3, 1, 14, 15, fm );
    s.W4 = fi( s1.W4, 1, 14, 12, fm );
    s.b4 = fi( s1.b4, 0, 14, 13, fm );
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
