/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: doFilter.c
 *
 * MATLAB Coder version            : 25.1
 * C/C++ source code generated on  : 22-Jan-2026 19:21:49
 */

/* Include Files */
#include "doFilter.h"
#include "SOSFilter.h"
#include "SystemCore.h"
#include "iir_filter_data.h"
#include "iir_filter_initialize.h"
#include "iir_filter_internal_types.h"

/* Variable Definitions */
static dsp_SOSFilter Hd;

/* Function Definitions */
/*
 * DOFILTER Filters input x and returns output y.
 *
 * Arguments    : const double x[1001]
 * Return Type  : void
 */
void doFilter(const double x[1001])
{
  double unusedExpr[1001];
  if (!isInitialized_iir_filter) {
    iir_filter_initialize();
  }
  /*  MATLAB Code */
  /*  Generated by MATLAB(R) 25.1 and DSP System Toolbox 25.1. */
  /*  Generated on: 22-Jan-2026 19:13:31 */
  /*  To generate C/C++ code from this function use the codegen command. */
  /*  Type 'help codegen' for more information. */
  SystemCore_step(&Hd, x, unusedExpr);
}

/*
 * Arguments    : void
 * Return Type  : void
 */
void doFilter_init(void)
{
  /*  The following code was used to design the filter coefficients: */
  /*  */
  /*  Fpass = 9600;   % Passband Frequency */
  /*  Fstop = 10000;  % Stopband Frequency */
  /*  Apass = 1;      % Passband Ripple (dB) */
  /*  Astop = 80;     % Stopband Attenuation (dB) */
  /*  Fs    = 48000;  % Sampling Frequency */
  /*  */
  /*  h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs); */
  /*  */
  /*  Hd = design(h, 'butter', ... */
  /*      'MatchExactly', 'stopband', ... */
  /*      'SystemObject', true); */
  SOSFilter_SOSFilter(&Hd);
}

/*
 * File trailer for doFilter.c
 *
 * [EOF]
 */
