-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\untitled\Integrador_tb.vhd
-- Created: 2026-01-22 10:34:46
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1e-08
-- Target subsystem base rate: 1e-08
-- Explicit user oversample request: 100x
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Integrador_tb
-- Source Path: 
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_textio.ALL;
USE IEEE.float_pkg.ALL;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
LIBRARY STD;
USE STD.textio.ALL;
LIBRARY work;
USE work.Integrador_pkg.ALL;
USE work.Integrador_tb_pkg.ALL;

ENTITY Integrador_tb IS
END Integrador_tb;


ARCHITECTURE rtl OF Integrador_tb IS

  -- Component Declarations
  COMPONENT Integrador
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          In1                             :   IN    std_logic_vector(63 DOWNTO 0);  -- double
          ce_out                          :   OUT   std_logic;
          Out1                            :   OUT   std_logic_vector(63 DOWNTO 0)  -- double
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Integrador
    USE ENTITY work.Integrador(rtl);

  -- Signals
  SIGNAL clk                              : std_logic;
  SIGNAL reset                            : std_logic;
  SIGNAL clk_enable                       : std_logic;
  SIGNAL Out1_done                        : std_logic;  -- ufix1
  SIGNAL ce_out                           : std_logic;
  SIGNAL Out1_done_enb                    : std_logic;  -- ufix1
  SIGNAL Out1_addr                        : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Out1_active                      : std_logic;  -- ufix1
  SIGNAL Repeating_Sequence_Stair_out1_addr : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Repeating_Sequence_Stair_out1_active : std_logic;  -- ufix1
  SIGNAL tb_enb_delay                     : std_logic;
  SIGNAL counter                          : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL phase_1_ctr                      : std_logic;
  SIGNAL phase_1                          : std_logic;
  SIGNAL Repeating_Sequence_Stair_out1_enb : std_logic;  -- ufix1
  SIGNAL Repeating_Sequence_Stair_out1_addr_delay_1 : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL tb_enb                           : std_logic;
  SIGNAL rawData_In1                      : std_logic_vector(63 DOWNTO 0);  -- ufix64
  SIGNAL holdData_In1                     : std_logic_vector(63 DOWNTO 0);  -- ufix64
  SIGNAL In1_offset                       : std_logic_vector(63 DOWNTO 0);  -- ufix64
  SIGNAL In1                              : std_logic_vector(63 DOWNTO 0);  -- ufix64
  SIGNAL snkDone                          : std_logic;
  SIGNAL snkDonen                         : std_logic;
  SIGNAL resetn                           : std_logic;
  SIGNAL notDone                          : std_logic;
  SIGNAL Out1                             : std_logic_vector(63 DOWNTO 0);  -- ufix64
  SIGNAL Out1_enb                         : std_logic;  -- ufix1
  SIGNAL Out1_lastAddr                    : std_logic;  -- ufix1
  SIGNAL Out1_addr_delay_1                : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Out1_expected                    : std_logic_vector(63 DOWNTO 0);  -- ufix64
  SIGNAL Out1_ref_hold                    : std_logic_vector(63 DOWNTO 0);  -- ufix64
  SIGNAL Out1_ref                         : std_logic_vector(63 DOWNTO 0);  -- ufix64
  SIGNAL Out1_testFailure                 : std_logic;  -- ufix1

BEGIN
  u_Integrador : Integrador
    PORT MAP( clk => clk,
              reset => reset,
              clk_enable => clk_enable,
              In1 => In1,  -- double
              ce_out => ce_out,
              Out1 => Out1  -- double
              );

  Out1_done_enb <= Out1_done AND ce_out;

  
  Out1_active <= '1' WHEN Out1_addr /= to_unsigned(16#A#, 4) ELSE
      '0';

  
  Repeating_Sequence_Stair_out1_active <= '1' WHEN Repeating_Sequence_Stair_out1_addr /= to_unsigned(16#A#, 4) ELSE
      '0';

  -- Count limited, Unsigned Counter
  --  initial value   = 1
  --  step value      = 1
  --  count to value  = 99
  slow_clock_enable_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      counter <= to_unsigned(16#01#, 7);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF tb_enb_delay = '1' THEN
        IF counter >= to_unsigned(16#63#, 7) THEN 
          counter <= to_unsigned(16#00#, 7);
        ELSE 
          counter <= counter + to_unsigned(16#01#, 7);
        END IF;
      END IF;
    END IF;
  END PROCESS slow_clock_enable_process;


  
  phase_1_ctr <= '1' WHEN counter = to_unsigned(16#01#, 7) ELSE
      '0';

  phase_1 <= phase_1_ctr AND tb_enb_delay;

  Repeating_Sequence_Stair_out1_enb <= Repeating_Sequence_Stair_out1_active AND (phase_1 AND tb_enb_delay);

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 10
  RepeatingSequenceStair_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Repeating_Sequence_Stair_out1_addr <= to_unsigned(16#0#, 4);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF Repeating_Sequence_Stair_out1_enb = '1' THEN
        IF Repeating_Sequence_Stair_out1_addr >= to_unsigned(16#A#, 4) THEN 
          Repeating_Sequence_Stair_out1_addr <= to_unsigned(16#0#, 4);
        ELSE 
          Repeating_Sequence_Stair_out1_addr <= Repeating_Sequence_Stair_out1_addr + to_unsigned(16#1#, 4);
        END IF;
      END IF;
    END IF;
  END PROCESS RepeatingSequenceStair_process;


  Repeating_Sequence_Stair_out1_addr_delay_1 <= Repeating_Sequence_Stair_out1_addr AFTER 1 ns;

  -- Data source for In1
  In1_fileread: PROCESS (Repeating_Sequence_Stair_out1_addr_delay_1, tb_enb_delay, phase_1)
    FILE fp: TEXT open READ_MODE is "In1.dat";
    VARIABLE l: LINE;
    VARIABLE read_data: std_logic_vector(63 DOWNTO 0);

  BEGIN
    IF tb_enb_delay /= '1' THEN
    ELSIF phase_1 = '1' AND NOT ENDFILE(fp) THEN
      READLINE(fp, l);
      HREAD(l, read_data);
    END IF;
    rawData_In1 <= std_logic_vector(read_data(63 DOWNTO 0));
  END PROCESS In1_fileread;

  -- holdData reg for Repeating_Sequence_Stair_out1
  stimuli_Repeating_Sequence_Stair_out1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      holdData_In1 <= (OTHERS => 'X');
    ELSIF clk'event AND clk = '1' THEN
      holdData_In1 <= rawData_In1;
    END IF;
  END PROCESS stimuli_Repeating_Sequence_Stair_out1_process;

  stimuli_Repeating_Sequence_Stair_out1_1: PROCESS (rawData_In1, phase_1)
  BEGIN
    IF phase_1 = '0' THEN
      In1_offset <= holdData_In1;
    ELSE
      In1_offset <= rawData_In1;
    END IF;
  END PROCESS stimuli_Repeating_Sequence_Stair_out1_1;

  In1 <= In1_offset AFTER 2 ns;

  snkDonen <=  NOT snkDone;

  resetn <=  NOT reset;

  tb_enb <= resetn AND snkDonen;

  -- Delay inside enable generation: register depth 1
  u_enable_delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tb_enb_delay <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      tb_enb_delay <= tb_enb;
    END IF;
  END PROCESS u_enable_delay_process;


  notDone <= tb_enb_delay AND snkDonen;

  clk_enable <= notDone AFTER 2 ns;

  reset_gen: PROCESS 
  BEGIN
    reset <= '1';
    WAIT FOR 20 ns;
    WAIT UNTIL clk'event AND clk = '1';
    WAIT FOR 2 ns;
    reset <= '0';
    WAIT;
  END PROCESS reset_gen;

  clk_gen: PROCESS 
  BEGIN
    clk <= '1';
    WAIT FOR 5 ns;
    clk <= '0';
    WAIT FOR 5 ns;
    IF snkDone = '1' THEN
      clk <= '1';
      WAIT FOR 5 ns;
      clk <= '0';
      WAIT FOR 5 ns;
      WAIT;
    END IF;
  END PROCESS clk_gen;

  Out1_enb <= ce_out AND Out1_active;

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 10
  c_4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Out1_addr <= to_unsigned(16#0#, 4);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF Out1_enb = '1' THEN
        IF Out1_addr >= to_unsigned(16#A#, 4) THEN 
          Out1_addr <= to_unsigned(16#0#, 4);
        ELSE 
          Out1_addr <= Out1_addr + to_unsigned(16#1#, 4);
        END IF;
      END IF;
    END IF;
  END PROCESS c_4_process;


  
  Out1_lastAddr <= '1' WHEN Out1_addr >= to_unsigned(16#A#, 4) ELSE
      '0';

  Out1_done <= Out1_lastAddr AND resetn;

  -- Delay to allow last sim cycle to complete
  checkDone_1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      snkDone <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF Out1_done_enb = '1' THEN
        snkDone <= Out1_done;
      END IF;
    END IF;
  END PROCESS checkDone_1_process;

  Out1_addr_delay_1 <= Out1_addr AFTER 1 ns;

  -- Data source for Out1_expected
  Out1_expected_fileread: PROCESS (Out1_addr_delay_1, tb_enb_delay)
    FILE fp: TEXT open READ_MODE is "Out1_expected.dat";
    VARIABLE l: LINE;
    VARIABLE read_data: std_logic_vector(63 DOWNTO 0);

  BEGIN
    IF tb_enb_delay /= '1' THEN
    ELSIF NOT ENDFILE(fp) THEN
      READLINE(fp, l);
      HREAD(l, read_data);
    END IF;
    Out1_expected <= std_logic_vector(read_data(63 DOWNTO 0));
  END PROCESS Out1_expected_fileread;

  -- Bypass register to hold Out1_ref
  DataHold_Out1_ref_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Out1_ref_hold <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' THEN
        Out1_ref_hold <= Out1_expected;
      END IF;
    END IF;
  END PROCESS DataHold_Out1_ref_process;

  
  Out1_ref <= Out1_ref_hold WHEN ce_out = '0' ELSE
      Out1_expected;

  Out1_checker: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Out1_testFailure <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' AND NOT isFloatDoubleEqual(Out1, Out1_ref, 9.9999999999999995e-08) THEN
        Out1_testFailure <= '1';
        ASSERT FALSE
          REPORT "Error in Out1: Expected " & to_hex(Out1_ref) & (" Actual " & to_hex(Out1))
          SEVERITY ERROR;
      END IF;
    END IF;
  END PROCESS Out1_checker;

  completed_msg: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF snkDone = '1' THEN
        IF Out1_testFailure = '0' THEN
          ASSERT FALSE
            REPORT "**************TEST COMPLETED (PASSED)**************"
            SEVERITY NOTE;
        ELSE
          ASSERT FALSE
            REPORT "**************TEST COMPLETED (FAILED)**************"
            SEVERITY NOTE;
        END IF;
      END IF;
    END IF;
  END PROCESS completed_msg;

END rtl;

