-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\untitled\Integrador_tc.vhd
-- Created: 2026-01-22 10:34:43
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Integrador_tc
-- Source Path: Integrador_tc
-- Hierarchy Level: 1
-- 
-- Master clock enable input: clk_enable
-- 
-- enb         : identical to clk_enable
-- enb_1_100_1 : 100x slower than clk with phase 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Integrador_tc IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        enb                               :   OUT   std_logic;
        enb_1_100_1                       :   OUT   std_logic
        );
END Integrador_tc;


ARCHITECTURE rtl OF Integrador_tc IS

  -- Signals
  SIGNAL count100                         : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL comp_1_tmp                       : std_logic;
  SIGNAL phase_1_tmp                      : std_logic;
  SIGNAL phase_1                          : std_logic;
  SIGNAL enb_1_100_1_1                    : std_logic;

BEGIN
  enb <= clk_enable;

  -- Count limited, Unsigned Counter
  --  initial value   = 1
  --  step value      = 1
  --  count to value  = 99
  counter_100_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      count100 <= to_unsigned(16#01#, 7);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF clk_enable = '1' THEN
        IF count100 >= to_unsigned(16#63#, 7) THEN 
          count100 <= to_unsigned(16#00#, 7);
        ELSE 
          count100 <= count100 + to_unsigned(16#01#, 7);
        END IF;
      END IF;
    END IF;
  END PROCESS counter_100_process;


  
  comp_1_tmp <= '1' WHEN count100 = to_unsigned(16#00#, 7) ELSE
      '0';

  phase_1_tmp <= comp_1_tmp AND clk_enable;

  phase_delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      phase_1 <= '1';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF clk_enable = '1' THEN
        phase_1 <= phase_1_tmp;
      END IF;
    END IF;
  END PROCESS phase_delay_process;


  enb_1_100_1_1 <= phase_1 AND clk_enable;

  enb_1_100_1 <= enb_1_100_1_1;

END rtl;

