-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\untitled\Integrador.vhd
-- Created: 2026-01-22 10:34:43
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1e-08
-- Target subsystem base rate: 1e-08
-- Explicit user oversample request: 100x
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1e-06
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1                          ce_out        1e-06
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Integrador
-- Source Path: untitled/Integrador
-- Hierarchy Level: 0
-- Model version: 1.0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Integrador IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        In1                               :   IN    std_logic_vector(63 DOWNTO 0);  -- double
        ce_out                            :   OUT   std_logic;
        Out1                              :   OUT   std_logic_vector(63 DOWNTO 0)  -- double
        );
END Integrador;


ARCHITECTURE rtl OF Integrador IS

  -- Component Declarations
  COMPONENT Integrador_tc
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          enb                             :   OUT   std_logic;
          enb_1_100_1                     :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT nfp_mul_double
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          nfp_in1                         :   IN    std_logic_vector(63 DOWNTO 0);  -- double
          nfp_in2                         :   IN    std_logic_vector(63 DOWNTO 0);  -- double
          nfp_out                         :   OUT   std_logic_vector(63 DOWNTO 0)  -- double
          );
  END COMPONENT;

  COMPONENT nfp_add_double
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          nfp_in1                         :   IN    std_logic_vector(63 DOWNTO 0);  -- double
          nfp_in2                         :   IN    std_logic_vector(63 DOWNTO 0);  -- double
          nfp_out                         :   OUT   std_logic_vector(63 DOWNTO 0)  -- double
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Integrador_tc
    USE ENTITY work.Integrador_tc(rtl);

  FOR ALL : nfp_mul_double
    USE ENTITY work.nfp_mul_double(rtl);

  FOR ALL : nfp_add_double
    USE ENTITY work.nfp_add_double(rtl);

  -- Signals
  SIGNAL enb_1_100_1                      : std_logic;
  SIGNAL enb                              : std_logic;
  SIGNAL kconst                           : std_logic_vector(63 DOWNTO 0);  -- ufix64
  SIGNAL Discrete_Time_Integrator_u_gain  : std_logic_vector(63 DOWNTO 0);  -- ufix64
  SIGNAL Discrete_Time_Integrator_x_reg   : std_logic_vector(63 DOWNTO 0);  -- ufix64
  SIGNAL Discrete_Time_Integrator_add_in  : std_logic_vector(63 DOWNTO 0);  -- ufix64
  SIGNAL Discrete_Time_Integrator_u_add   : std_logic_vector(63 DOWNTO 0);  -- ufix64
  SIGNAL Discrete_Time_Integrator_u_sat   : std_logic_vector(63 DOWNTO 0);  -- ufix64
  SIGNAL Discrete_Time_Integrator_reg_bypass_reg : std_logic_vector(63 DOWNTO 0);  -- ufix64
  SIGNAL Discrete_Time_Integrator_x_reg_1 : std_logic_vector(63 DOWNTO 0);  -- ufix64
  SIGNAL t_bypass_reg                     : std_logic_vector(63 DOWNTO 0);  -- ufix64
  SIGNAL Discrete_Time_Integrator_out1    : std_logic_vector(63 DOWNTO 0);  -- ufix64

BEGIN
  u_Integrador_tc : Integrador_tc
    PORT MAP( clk => clk,
              reset => reset,
              clk_enable => clk_enable,
              enb => enb,
              enb_1_100_1 => enb_1_100_1
              );

  u_nfp_mul_comp : nfp_mul_double
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              nfp_in1 => kconst,  -- double
              nfp_in2 => In1,  -- double
              nfp_out => Discrete_Time_Integrator_u_gain  -- double
              );

  u_nfp_add_comp : nfp_add_double
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              nfp_in1 => Discrete_Time_Integrator_add_in,  -- double
              nfp_in2 => Discrete_Time_Integrator_u_gain,  -- double
              nfp_out => Discrete_Time_Integrator_u_add  -- double
              );

  kconst <= X"3eb0c6f7a0b5ed8d";

  delayMatch_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Discrete_Time_Integrator_add_in <= X"0000000000000000";
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Discrete_Time_Integrator_add_in <= Discrete_Time_Integrator_x_reg;
      END IF;
    END IF;
  END PROCESS delayMatch_process;


  crp_out_delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Discrete_Time_Integrator_u_sat <= X"0000000000000000";
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Discrete_Time_Integrator_u_sat <= Discrete_Time_Integrator_u_add;
      END IF;
    END IF;
  END PROCESS crp_out_delay_process;


  Discrete_Time_Integrator_reg_bypass_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Discrete_Time_Integrator_reg_bypass_reg <= X"0000000000000000";
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_100_1 = '1' THEN
        Discrete_Time_Integrator_reg_bypass_reg <= Discrete_Time_Integrator_u_sat;
      END IF;
    END IF;
  END PROCESS Discrete_Time_Integrator_reg_bypass_process;

  
  Discrete_Time_Integrator_x_reg_1 <= Discrete_Time_Integrator_u_sat WHEN enb_1_100_1 = '1' ELSE
      Discrete_Time_Integrator_reg_bypass_reg;

  Discrete_Time_Integrator_x_reg <= Discrete_Time_Integrator_x_reg_1;

  t_bypass_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      t_bypass_reg <= X"0000000000000000";
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_100_1 = '1' THEN
        t_bypass_reg <= Discrete_Time_Integrator_x_reg;
      END IF;
    END IF;
  END PROCESS t_bypass_process;

  
  Discrete_Time_Integrator_out1 <= Discrete_Time_Integrator_x_reg WHEN enb_1_100_1 = '1' ELSE
      t_bypass_reg;

  Out1 <= Discrete_Time_Integrator_out1;

  ce_out <= enb_1_100_1;

END rtl;

