-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\Moving_Average_sim\Moving_Average.vhd
-- Created: 2025-09-08 20:48:28
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.0001
-- Target subsystem base rate: 0.0001
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.0001
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Output                        ce_out        0.0001
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Moving_Average
-- Source Path: Moving_Average_sim/Moving Average
-- Hierarchy Level: 0
-- Model version: 1.1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Moving_Average_pkg.ALL;

ENTITY Moving_Average IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        Input                             :   IN    std_logic_vector(63 DOWNTO 0);  -- double
        ce_out                            :   OUT   std_logic;
        Output                            :   OUT   std_logic_vector(63 DOWNTO 0)  -- double
        );
END Moving_Average;


ARCHITECTURE rtl OF Moving_Average IS

  -- Component Declarations
  COMPONENT nfp_gain_pow2_double
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          nfp_in1                         :   IN    std_logic_vector(63 DOWNTO 0);  -- double
          nfp_in2                         :   IN    std_logic;  -- ufix1
          nfp_in3                         :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12
          nfp_out                         :   OUT   std_logic_vector(63 DOWNTO 0)  -- double
          );
  END COMPONENT;

  COMPONENT nfp_add_double
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          nfp_in1                         :   IN    std_logic_vector(63 DOWNTO 0);  -- double
          nfp_in2                         :   IN    std_logic_vector(63 DOWNTO 0);  -- double
          nfp_out                         :   OUT   std_logic_vector(63 DOWNTO 0)  -- double
          );
  END COMPONENT;

  COMPONENT nfp_uminus_double
    PORT( nfp_in                          :   IN    std_logic_vector(63 DOWNTO 0);  -- double
          nfp_out                         :   OUT   std_logic_vector(63 DOWNTO 0)  -- double
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : nfp_gain_pow2_double
    USE ENTITY work.nfp_gain_pow2_double(rtl);

  FOR ALL : nfp_add_double
    USE ENTITY work.nfp_add_double(rtl);

  FOR ALL : nfp_uminus_double
    USE ENTITY work.nfp_uminus_double(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL delayMatch_reg                   : vector_of_std_logic_vector64(0 TO 1);  -- ufix64 [2]
  SIGNAL Rate_Transition_out1             : std_logic_vector(63 DOWNTO 0);  -- ufix64
  SIGNAL pw2_sign_const                   : std_logic;  -- ufix1
  SIGNAL pw2_shift_const                  : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Gain2_out1                       : std_logic_vector(63 DOWNTO 0);  -- ufix64
  SIGNAL Sum_out1                         : std_logic_vector(63 DOWNTO 0);  -- ufix64
  SIGNAL Gain_out1                        : std_logic_vector(63 DOWNTO 0);  -- ufix64
  SIGNAL delayMatch1_reg                  : vector_of_std_logic_vector64(0 TO 10);  -- ufix64 [11]
  SIGNAL Gain_out1_1                      : std_logic_vector(63 DOWNTO 0);  -- ufix64
  SIGNAL Sum1_out1                        : std_logic_vector(63 DOWNTO 0);  -- ufix64
  SIGNAL pw2_sign_const_1                 : std_logic;  -- ufix1
  SIGNAL pw2_shift_const_1                : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Gain1_out1                       : std_logic_vector(63 DOWNTO 0);  -- ufix64
  SIGNAL delayMatch2_reg                  : vector_of_std_logic_vector64(0 TO 19);  -- ufix64 [20]
  SIGNAL Gain1_out1_1                     : std_logic_vector(63 DOWNTO 0);  -- ufix64
  SIGNAL Sum2_out1                        : std_logic_vector(63 DOWNTO 0);  -- ufix64

BEGIN
  u_nfp_gain_pow2_double : nfp_gain_pow2_double
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              nfp_in1 => Input,  -- double
              nfp_in2 => pw2_sign_const,  -- ufix1
              nfp_in3 => std_logic_vector(pw2_shift_const),  -- sfix12
              nfp_out => Gain2_out1  -- double
              );

  u_nfp_add_comp : nfp_add_double
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              nfp_in1 => Rate_Transition_out1,  -- double
              nfp_in2 => Gain2_out1,  -- double
              nfp_out => Sum_out1  -- double
              );

  u_nfp_uminus_comp : nfp_uminus_double
    PORT MAP( nfp_in => Gain2_out1,  -- double
              nfp_out => Gain_out1  -- double
              );

  u_nfp_add_comp_1 : nfp_add_double
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              nfp_in1 => Sum_out1,  -- double
              nfp_in2 => Gain_out1_1,  -- double
              nfp_out => Sum1_out1  -- double
              );

  u_nfp_gain_pow2_double_1 : nfp_gain_pow2_double
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              nfp_in1 => Gain_out1,  -- double
              nfp_in2 => pw2_sign_const_1,  -- ufix1
              nfp_in3 => std_logic_vector(pw2_shift_const_1),  -- sfix12
              nfp_out => Gain1_out1  -- double
              );

  u_nfp_add_comp_2 : nfp_add_double
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              nfp_in1 => Sum1_out1,  -- double
              nfp_in2 => Gain1_out1_1,  -- double
              nfp_out => Sum2_out1  -- double
              );

  enb <= clk_enable;

  delayMatch_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg <= (OTHERS => X"0000000000000000");
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg(0) <= Input;
        delayMatch_reg(1) <= delayMatch_reg(0);
      END IF;
    END IF;
  END PROCESS delayMatch_process;

  Rate_Transition_out1 <= delayMatch_reg(1);

  pw2_sign_const <= '0';

  pw2_shift_const <= to_signed(16#001#, 12);

  delayMatch1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch1_reg <= (OTHERS => X"0000000000000000");
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch1_reg(0) <= Gain_out1;
        delayMatch1_reg(1 TO 10) <= delayMatch1_reg(0 TO 9);
      END IF;
    END IF;
  END PROCESS delayMatch1_process;

  Gain_out1_1 <= delayMatch1_reg(10);

  pw2_sign_const_1 <= '0';

  pw2_shift_const_1 <= to_signed(16#002#, 12);

  delayMatch2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch2_reg <= (OTHERS => X"0000000000000000");
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch2_reg(0) <= Gain1_out1;
        delayMatch2_reg(1 TO 19) <= delayMatch2_reg(0 TO 18);
      END IF;
    END IF;
  END PROCESS delayMatch2_process;

  Gain1_out1_1 <= delayMatch2_reg(19);

  Output <= Sum2_out1;

  ce_out <= clk_enable;

END rtl;

