-- -------------------------------------------------------------
-- 
-- File Name: C:\curso_HDL_Vanderlei\Advanced-Digital-System-Development-Using-MATLAB-C-and-VHDL\1_LINGUAGENS_HDL_E_VHDL\6_EXEMPLO_FILTRO_FIR_HDL_CODER\hdlsrc\filter_low_pass_simulink\Discrete_FIR_Filter1.vhd
-- Created: 2025-09-10 16:42:28
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Discrete_FIR_Filter1
-- Source Path: filter_low_pass_simulink/Discrete FIR Filter1
-- Hierarchy Level: 1
-- Model version: 1.5
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Discrete_FIR_Filter1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Discrete_FIR_Filter1_in           :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        Discrete_FIR_Filter1_out          :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
        );
END Discrete_FIR_Filter1;


ARCHITECTURE rtl OF Discrete_FIR_Filter1 IS

  -- Component Declarations
  COMPONENT nfp_gain_pow2_single
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          nfp_in1                         :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          nfp_in2                         :   IN    std_logic;  -- ufix1
          nfp_in3                         :   IN    std_logic_vector(8 DOWNTO 0);  -- sfix9
          nfp_out                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : nfp_gain_pow2_single
    USE ENTITY work.nfp_gain_pow2_single(rtl);

  -- Signals
  SIGNAL initcounter                      : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL initcompare                      : std_logic;
  SIGNAL initcompare11                    : std_logic;
  SIGNAL Discrete_FIR_Filter1_outconst0   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL pw2_sign_const                   : std_logic;  -- ufix1
  SIGNAL pw2_shift_const                  : signed(8 DOWNTO 0);  -- sfix9
  SIGNAL gain0                            : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL delay1                           : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL pw2_sign_const_1                 : std_logic;  -- ufix1
  SIGNAL pw2_shift_const_1                : signed(8 DOWNTO 0);  -- sfix9
  SIGNAL gain1                            : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Discrete_FIR_Filter1_outipOut    : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_nfp_gain_pow2_single : nfp_gain_pow2_single
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              nfp_in1 => Discrete_FIR_Filter1_in,  -- single
              nfp_in2 => pw2_sign_const,  -- ufix1
              nfp_in3 => std_logic_vector(pw2_shift_const),  -- sfix9
              nfp_out => gain0  -- single
              );

  u_nfp_gain_pow2_single_1 : nfp_gain_pow2_single
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              nfp_in1 => delay1,  -- single
              nfp_in2 => pw2_sign_const_1,  -- ufix1
              nfp_in3 => std_logic_vector(pw2_shift_const_1),  -- sfix9
              nfp_out => gain1  -- single
              );

  alterafpf_add_single_1 : ENTITY work.alterafpf_add_single
    PORT MAP( a => gain0,  -- single
              b => gain1,  -- single
              clk => clk,
              en(0) => enb,
              areset => reset,
              q => Discrete_FIR_Filter1_outipOut  -- single
              );

  
  initcompare <= '1' WHEN initcounter < to_unsigned(16#B#, 4) ELSE
      '0';

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 11
  ctr_0_11_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      initcounter <= to_unsigned(16#0#, 4);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF initcompare = '1' THEN 
          IF initcounter >= to_unsigned(16#B#, 4) THEN 
            initcounter <= to_unsigned(16#0#, 4);
          ELSE 
            initcounter <= initcounter + to_unsigned(16#1#, 4);
          END IF;
        END IF;
      END IF;
    END IF;
  END PROCESS ctr_0_11_process;


  
  initcompare11 <= '1' WHEN initcounter >= to_unsigned(16#B#, 4) ELSE
      '0';

  Discrete_FIR_Filter1_outconst0 <= X"00000000";

  pw2_sign_const <= '0';

  pw2_shift_const <= to_signed(-16#001#, 9);

  unit_delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay1 <= X"00000000";
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delay1 <= Discrete_FIR_Filter1_in;
      END IF;
    END IF;
  END PROCESS unit_delay_process;


  pw2_sign_const_1 <= '0';

  pw2_shift_const_1 <= to_signed(-16#001#, 9);

  
  Discrete_FIR_Filter1_out <= Discrete_FIR_Filter1_outconst0 WHEN initcompare11 = '0' ELSE
      Discrete_FIR_Filter1_outipOut;

END rtl;

