-- -------------------------------------------------------------
-- 
-- File Name: C:\curso_HDL_Vanderlei\Advanced-Digital-System-Development-Using-MATLAB-C-and-VHDL\1_LINGUAGENS_HDL_E_VHDL\6_EXEMPLO_FILTRO_FIR_HDL_CODER\hdlsrc\filter_low_pass_simulink\filter_low_pass_simulink.vhd
-- Created: 2025-09-10 16:42:28
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 2.27273e-05
-- Target subsystem base rate: 2.27273e-05
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        2.27273e-05
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1                          ce_out        2.27273e-05
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: filter_low_pass_simulink
-- Source Path: filter_low_pass_simulink
-- Hierarchy Level: 0
-- Model version: 1.5
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY filter_low_pass_simulink IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        In1                               :   IN    std_logic_vector(31 DOWNTO 0);  -- single
        ce_out                            :   OUT   std_logic;
        Out1                              :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
        );
END filter_low_pass_simulink;


ARCHITECTURE rtl OF filter_low_pass_simulink IS

  -- Component Declarations
  COMPONENT Discrete_FIR_Filter1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Discrete_FIR_Filter1_in         :   IN    std_logic_vector(31 DOWNTO 0);  -- single
          Discrete_FIR_Filter1_out        :   OUT   std_logic_vector(31 DOWNTO 0)  -- single
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Discrete_FIR_Filter1
    USE ENTITY work.Discrete_FIR_Filter1(rtl);

  -- Signals
  SIGNAL Discrete_FIR_Filter1_out1        : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_Discrete_FIR_Filter1 : Discrete_FIR_Filter1
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              Discrete_FIR_Filter1_in => In1,  -- single
              Discrete_FIR_Filter1_out => Discrete_FIR_Filter1_out1  -- single
              );

  Out1 <= Discrete_FIR_Filter1_out1;

  ce_out <= clk_enable;

END rtl;

