-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\thiag\OneDrive\documentos\MATLAB\codegen\hdl_IP\hdlsrc\dsphdl_BiquadFilter.vhd
-- Created: 2025-09-19 14:39:26
-- 
-- Generated by MATLAB 25.2, MATLAB Coder 25.2 and HDL Coder 25.2
-- 
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: dsphdl_BiquadFilter
-- Source Path: hdl_IP/dsphdl.BiquadFilter
-- Hierarchy Level: 1
-- 
-- Biquad Filter
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY dsphdl_BiquadFilter IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dataIn                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        validIn                           :   IN    std_logic;
        dataOut                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        validOut                          :   OUT   std_logic
        );
END dsphdl_BiquadFilter;


ARCHITECTURE rtl OF dsphdl_BiquadFilter IS

  -- Component Declarations
  COMPONENT BiquadDF2Section1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          validIn                         :   IN    std_logic;
          dataOut                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT BiquadDF2Section2
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          validIn                         :   IN    std_logic;
          dataOut                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT BiquadDF2Section3
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          validIn                         :   IN    std_logic;
          dataOut                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT BiquadDF2Section4
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          validIn                         :   IN    std_logic;
          dataOut                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT BiquadDF2Section5
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          validIn                         :   IN    std_logic;
          dataOut                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : BiquadDF2Section1
    USE ENTITY work.BiquadDF2Section1(rtl);

  FOR ALL : BiquadDF2Section2
    USE ENTITY work.BiquadDF2Section2(rtl);

  FOR ALL : BiquadDF2Section3
    USE ENTITY work.BiquadDF2Section3(rtl);

  FOR ALL : BiquadDF2Section4
    USE ENTITY work.BiquadDF2Section4(rtl);

  FOR ALL : BiquadDF2Section5
    USE ENTITY work.BiquadDF2Section5(rtl);

  -- Signals
  SIGNAL dataIn_signed                    : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL sec0reg                          : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL sec0mul                          : signed(31 DOWNTO 0);  -- sfix32_En22
  SIGNAL sec0mulreg                       : signed(31 DOWNTO 0);  -- sfix32_En22
  SIGNAL sec0dtc                          : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL sec0out                          : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL sec0validreg                     : std_logic;
  SIGNAL sec0mulvalidreg                  : std_logic;
  SIGNAL sec0validout                     : std_logic;
  SIGNAL sec1out                          : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL sec1validout                     : std_logic;
  SIGNAL sec1out_signed                   : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL sec1mul                          : signed(31 DOWNTO 0);  -- sfix32_En22
  SIGNAL sec1mulreg                       : signed(31 DOWNTO 0);  -- sfix32_En22
  SIGNAL sec1dtc                          : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL sec1out_1                        : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL sec1mulvalidreg                  : std_logic;
  SIGNAL sec1validout_1                   : std_logic;
  SIGNAL sec2out                          : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL sec2validout                     : std_logic;
  SIGNAL sec2out_signed                   : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL sec2mul                          : signed(31 DOWNTO 0);  -- sfix32_En22
  SIGNAL sec2mulreg                       : signed(31 DOWNTO 0);  -- sfix32_En22
  SIGNAL sec2dtc                          : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL sec2out_1                        : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL sec2mulvalidreg                  : std_logic;
  SIGNAL sec2validout_1                   : std_logic;
  SIGNAL sec3out                          : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL sec3validout                     : std_logic;
  SIGNAL sec3out_signed                   : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL sec3mul                          : signed(31 DOWNTO 0);  -- sfix32_En22
  SIGNAL sec3mulreg                       : signed(31 DOWNTO 0);  -- sfix32_En22
  SIGNAL sec3dtc                          : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL sec3out_1                        : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL sec3mulvalidreg                  : std_logic;
  SIGNAL sec3validout_1                   : std_logic;
  SIGNAL sec4out                          : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL sec4validout                     : std_logic;
  SIGNAL sec4out_signed                   : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL sec4mul                          : signed(31 DOWNTO 0);  -- sfix32_En22
  SIGNAL sec4mulreg                       : signed(31 DOWNTO 0);  -- sfix32_En22
  SIGNAL sec4dtc                          : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL sec4out_1                        : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL sec4mulvalidreg                  : std_logic;
  SIGNAL sec4validout_1                   : std_logic;
  SIGNAL sec5out                          : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL sec5validout                     : std_logic;
  SIGNAL sec5mulvalidreg                  : std_logic;
  SIGNAL sec5validout_1                   : std_logic;
  SIGNAL zerooutconst                     : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL sec5out_signed                   : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL sec5mul                          : signed(31 DOWNTO 0);  -- sfix32_En22
  SIGNAL sec5mulreg                       : signed(31 DOWNTO 0);  -- sfix32_En22
  SIGNAL sec5dtc                          : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL sec5out_1                        : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL preout                           : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL dataOut_tmp                      : signed(15 DOWNTO 0);  -- sfix16_En8

BEGIN
  u_BiquadSection1_inst : BiquadDF2Section1
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => std_logic_vector(sec0out),  -- sfix16_En8
              validIn => sec0validout,
              dataOut => sec1out,  -- sfix16_En8
              validOut => sec1validout
              );

  u_BiquadSection2_inst : BiquadDF2Section2
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => std_logic_vector(sec1out_1),  -- sfix16_En8
              validIn => sec1validout_1,
              dataOut => sec2out,  -- sfix16_En8
              validOut => sec2validout
              );

  u_BiquadSection3_inst : BiquadDF2Section3
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => std_logic_vector(sec2out_1),  -- sfix16_En8
              validIn => sec2validout_1,
              dataOut => sec3out,  -- sfix16_En8
              validOut => sec3validout
              );

  u_BiquadSection4_inst : BiquadDF2Section4
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => std_logic_vector(sec3out_1),  -- sfix16_En8
              validIn => sec3validout_1,
              dataOut => sec4out,  -- sfix16_En8
              validOut => sec4validout
              );

  u_BiquadSection5_inst : BiquadDF2Section5
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn => std_logic_vector(sec4out_1),  -- sfix16_En8
              validIn => sec4validout_1,
              dataOut => sec5out,  -- sfix16_En8
              validOut => sec5validout
              );

  dataIn_signed <= signed(dataIn);

  sec0dataregister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec0reg <= to_signed(16#0000#, 16);
      ELSIF enb = '1' THEN
        sec0reg <= dataIn_signed;
      END IF;
    END IF;
  END PROCESS sec0dataregister_process;


  sec0mul <= to_signed(16#1355#, 16) * sec0reg;

  sec0muldataregister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec0mulreg <= to_signed(0, 32);
      ELSIF enb = '1' THEN
        sec0mulreg <= sec0mul;
      END IF;
    END IF;
  END PROCESS sec0muldataregister_process;


  sec0dtc <= sec0mulreg(29 DOWNTO 14);

  sec0OutRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec0out <= to_signed(16#0000#, 16);
      ELSIF enb = '1' THEN
        sec0out <= sec0dtc;
      END IF;
    END IF;
  END PROCESS sec0OutRegister_process;


  sec0validregister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec0validreg <= '0';
      ELSIF enb = '1' THEN
        sec0validreg <= validIn;
      END IF;
    END IF;
  END PROCESS sec0validregister_process;


  sec0mulvalidregister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec0mulvalidreg <= '0';
      ELSIF enb = '1' THEN
        sec0mulvalidreg <= sec0validreg;
      END IF;
    END IF;
  END PROCESS sec0mulvalidregister_process;


  sec0validoutregister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec0validout <= '0';
      ELSIF enb = '1' THEN
        sec0validout <= sec0mulvalidreg;
      END IF;
    END IF;
  END PROCESS sec0validoutregister_process;


  sec1out_signed <= signed(sec1out);

  sec1mul <= to_signed(16#0F82#, 16) * sec1out_signed;

  sec1muldataregister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec1mulreg <= to_signed(0, 32);
      ELSIF enb = '1' THEN
        sec1mulreg <= sec1mul;
      END IF;
    END IF;
  END PROCESS sec1muldataregister_process;


  sec1dtc <= sec1mulreg(29 DOWNTO 14);

  sec1OutRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec1out_1 <= to_signed(16#0000#, 16);
      ELSIF enb = '1' THEN
        sec1out_1 <= sec1dtc;
      END IF;
    END IF;
  END PROCESS sec1OutRegister_process;


  sec1mulvalidregister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec1mulvalidreg <= '0';
      ELSIF enb = '1' THEN
        sec1mulvalidreg <= sec1validout;
      END IF;
    END IF;
  END PROCESS sec1mulvalidregister_process;


  sec1validoutregister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec1validout_1 <= '0';
      ELSIF enb = '1' THEN
        sec1validout_1 <= sec1mulvalidreg;
      END IF;
    END IF;
  END PROCESS sec1validoutregister_process;


  sec2out_signed <= signed(sec2out);

  sec2mul <= to_signed(16#0D46#, 16) * sec2out_signed;

  sec2muldataregister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec2mulreg <= to_signed(0, 32);
      ELSIF enb = '1' THEN
        sec2mulreg <= sec2mul;
      END IF;
    END IF;
  END PROCESS sec2muldataregister_process;


  sec2dtc <= sec2mulreg(29 DOWNTO 14);

  sec2OutRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec2out_1 <= to_signed(16#0000#, 16);
      ELSIF enb = '1' THEN
        sec2out_1 <= sec2dtc;
      END IF;
    END IF;
  END PROCESS sec2OutRegister_process;


  sec2mulvalidregister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec2mulvalidreg <= '0';
      ELSIF enb = '1' THEN
        sec2mulvalidreg <= sec2validout;
      END IF;
    END IF;
  END PROCESS sec2mulvalidregister_process;


  sec2validoutregister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec2validout_1 <= '0';
      ELSIF enb = '1' THEN
        sec2validout_1 <= sec2mulvalidreg;
      END IF;
    END IF;
  END PROCESS sec2validoutregister_process;


  sec3out_signed <= signed(sec3out);

  sec3mul <= to_signed(16#0C05#, 16) * sec3out_signed;

  sec3muldataregister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec3mulreg <= to_signed(0, 32);
      ELSIF enb = '1' THEN
        sec3mulreg <= sec3mul;
      END IF;
    END IF;
  END PROCESS sec3muldataregister_process;


  sec3dtc <= sec3mulreg(29 DOWNTO 14);

  sec3OutRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec3out_1 <= to_signed(16#0000#, 16);
      ELSIF enb = '1' THEN
        sec3out_1 <= sec3dtc;
      END IF;
    END IF;
  END PROCESS sec3OutRegister_process;


  sec3mulvalidregister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec3mulvalidreg <= '0';
      ELSIF enb = '1' THEN
        sec3mulvalidreg <= sec3validout;
      END IF;
    END IF;
  END PROCESS sec3mulvalidregister_process;


  sec3validoutregister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec3validout_1 <= '0';
      ELSIF enb = '1' THEN
        sec3validout_1 <= sec3mulvalidreg;
      END IF;
    END IF;
  END PROCESS sec3validoutregister_process;


  sec4out_signed <= signed(sec4out);

  sec4mul <= to_signed(16#0B73#, 16) * sec4out_signed;

  sec4muldataregister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec4mulreg <= to_signed(0, 32);
      ELSIF enb = '1' THEN
        sec4mulreg <= sec4mul;
      END IF;
    END IF;
  END PROCESS sec4muldataregister_process;


  sec4dtc <= sec4mulreg(29 DOWNTO 14);

  sec4OutRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec4out_1 <= to_signed(16#0000#, 16);
      ELSIF enb = '1' THEN
        sec4out_1 <= sec4dtc;
      END IF;
    END IF;
  END PROCESS sec4OutRegister_process;


  sec4mulvalidregister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec4mulvalidreg <= '0';
      ELSIF enb = '1' THEN
        sec4mulvalidreg <= sec4validout;
      END IF;
    END IF;
  END PROCESS sec4mulvalidregister_process;


  sec4validoutregister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec4validout_1 <= '0';
      ELSIF enb = '1' THEN
        sec4validout_1 <= sec4mulvalidreg;
      END IF;
    END IF;
  END PROCESS sec4validoutregister_process;


  sec5mulvalidregister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec5mulvalidreg <= '0';
      ELSIF enb = '1' THEN
        sec5mulvalidreg <= sec5validout;
      END IF;
    END IF;
  END PROCESS sec5mulvalidregister_process;


  sec5validoutregister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec5validout_1 <= '0';
      ELSIF enb = '1' THEN
        sec5validout_1 <= sec5mulvalidreg;
      END IF;
    END IF;
  END PROCESS sec5validoutregister_process;


  zerooutconst <= to_signed(16#0000#, 16);

  sec5out_signed <= signed(sec5out);

  sec5mul <= resize(sec5out_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 32);

  sec5muldataregister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec5mulreg <= to_signed(0, 32);
      ELSIF enb = '1' THEN
        sec5mulreg <= sec5mul;
      END IF;
    END IF;
  END PROCESS sec5muldataregister_process;


  sec5dtc <= sec5mulreg(29 DOWNTO 14);

  sec5OutRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        sec5out_1 <= to_signed(16#0000#, 16);
      ELSIF enb = '1' THEN
        sec5out_1 <= sec5dtc;
      END IF;
    END IF;
  END PROCESS sec5OutRegister_process;


  
  preout <= zerooutconst WHEN sec5validout_1 = '0' ELSE
      sec5out_1;

  OutRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        dataOut_tmp <= to_signed(16#0000#, 16);
      ELSIF enb = '1' THEN
        dataOut_tmp <= preout;
      END IF;
    END IF;
  END PROCESS OutRegister_process;


  dataOut <= std_logic_vector(dataOut_tmp);

  ValidOutRegister_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        validOut <= '0';
      ELSIF enb = '1' THEN
        validOut <= sec5validout_1;
      END IF;
    END IF;
  END PROCESS ValidOutRegister_process;


END rtl;

