-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\thiag\OneDrive\documentos\MATLAB\codegen\hdl_IP\hdlsrc\hdl_IP_tb.vhd
-- Created: 2025-09-22 09:42:54
-- 
-- Generated by MATLAB 25.2, MATLAB Coder 25.2 and HDL Coder 25.2
-- 
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Design base rate: 1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: hdl_IP_tb
-- Source Path: 
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_textio.ALL;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
LIBRARY STD;
USE STD.textio.ALL;
USE work.hdl_IP_tb_pkg.ALL;

ENTITY hdl_IP_tb IS
END hdl_IP_tb;


ARCHITECTURE rtl OF hdl_IP_tb IS

  -- Component Declarations
  COMPONENT hdl_IP
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          validIn                         :   IN    std_logic;
          ce_out                          :   OUT   std_logic;
          dataOut                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : hdl_IP
    USE ENTITY work.hdl_IP(rtl);

  -- Signals
  SIGNAL clk                              : std_logic;
  SIGNAL reset                            : std_logic;
  SIGNAL enb                              : std_logic;
  SIGNAL rawData_validIn                  : std_logic;
  SIGNAL validOut_done                    : std_logic;  -- ufix1
  SIGNAL rdEnb                            : std_logic;
  SIGNAL validOut_done_enb                : std_logic;  -- ufix1
  SIGNAL dataOut_addr                     : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL validOut_lastAddr                : std_logic;  -- ufix1
  SIGNAL resetn                           : std_logic;
  SIGNAL check2_done                      : std_logic;  -- ufix1
  SIGNAL dataOut_done                     : std_logic;  -- ufix1
  SIGNAL dataOut_done_enb                 : std_logic;  -- ufix1
  SIGNAL dataOut_active                   : std_logic;  -- ufix1
  SIGNAL holdData_validIn                 : std_logic;
  SIGNAL validIn_offset                   : std_logic;
  SIGNAL validIn_1                        : std_logic;
  SIGNAL dataIn_addr                      : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL dataIn_active                    : std_logic;  -- ufix1
  SIGNAL tb_enb                           : std_logic;
  SIGNAL dataIn_enb                       : std_logic;  -- ufix1
  SIGNAL dataIn_addr_delay_1              : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL rawData_dataIn                   : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL holdData_dataIn                  : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL dataIn_offset                    : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL dataIn_1                         : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL dataIn_2                         : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL snkDone                          : std_logic;
  SIGNAL snkDonen                         : std_logic;
  SIGNAL ce_out                           : std_logic;
  SIGNAL dataOut                          : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL validOut                         : std_logic;
  SIGNAL dataOut_enb                      : std_logic;  -- ufix1
  SIGNAL dataOut_lastAddr                 : std_logic;  -- ufix1
  SIGNAL check1_done                      : std_logic;  -- ufix1
  SIGNAL dataOut_signed                   : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL dataOut_addr_delay_1             : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL dataOut_expected                 : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL dataOut_ref                      : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL dataOut_testFailure              : std_logic;  -- ufix1
  SIGNAL validOut_addr_delay_1            : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL validOut_expected                : std_logic;
  SIGNAL validOut_ref                     : std_logic;
  SIGNAL validOut_testFailure             : std_logic;  -- ufix1
  SIGNAL testFailure                      : std_logic;  -- ufix1

BEGIN
  u_hdl_IP : hdl_IP
    PORT MAP( clk => clk,
              reset => reset,
              clk_enable => enb,
              dataIn => dataIn_2,  -- sfix16_En8
              validIn => validIn_1,
              ce_out => ce_out,
              dataOut => dataOut,  -- sfix16_En8
              validOut => validOut
              );

  -- Data source for validIn
  rawData_validIn <= '1';

  validOut_done_enb <= validOut_done AND rdEnb;

  
  validOut_lastAddr <= '1' WHEN dataOut_addr = to_unsigned(16#3FF#, 10) ELSE
      '0';

  validOut_done <= validOut_lastAddr AND resetn;

  -- Delay to allow last sim cycle to complete
  checkDone_2_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF reset = '1' THEN
        check2_done <= '0';
      ELSIF validOut_done_enb = '1' THEN
        check2_done <= validOut_done;
      END IF;
    END IF;
  END PROCESS checkDone_2_process;

  dataOut_done_enb <= dataOut_done AND rdEnb;

  
  dataOut_active <= '1' WHEN dataOut_addr /= to_unsigned(16#3FF#, 10) ELSE
      '0';

  -- holdData reg for validIn
  stimuli_validIn_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF reset = '1' THEN
        holdData_validIn <= 'X';
      ELSE
        holdData_validIn <= rawData_validIn;
      END IF;
    END IF;
  END PROCESS stimuli_validIn_process;

  stimuli_validIn_1: PROCESS (rawData_validIn, rdEnb)
  BEGIN
    IF rdEnb = '0' THEN
      validIn_offset <= holdData_validIn;
    ELSE
      validIn_offset <= rawData_validIn;
    END IF;
  END PROCESS stimuli_validIn_1;

  validIn_1 <= validIn_offset AFTER 2 ns;

  
  dataIn_active <= '1' WHEN dataIn_addr /= to_unsigned(16#3FF#, 10) ELSE
      '0';

  dataIn_enb <= dataIn_active AND (rdEnb AND tb_enb);

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 1023
  dataIn_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        dataIn_addr <= to_unsigned(16#000#, 10);
      ELSIF dataIn_enb = '1' THEN
        dataIn_addr <= dataIn_addr + to_unsigned(16#001#, 10);
      END IF;
    END IF;
  END PROCESS dataIn_process;


  dataIn_addr_delay_1 <= dataIn_addr AFTER 1 ns;

  -- Data source for dataIn
  dataIn_fileread: PROCESS (dataIn_addr_delay_1, tb_enb, rdEnb)
    FILE fp: TEXT open READ_MODE is "dataIn.dat";
    VARIABLE l: LINE;
    VARIABLE read_data: std_logic_vector(15 DOWNTO 0);

  BEGIN
    IF tb_enb /= '1' THEN
    ELSIF rdEnb = '1' AND NOT ENDFILE(fp) THEN
      READLINE(fp, l);
      HREAD(l, read_data);
    END IF;
    rawData_dataIn <= signed(read_data(15 DOWNTO 0));
  END PROCESS dataIn_fileread;

  -- holdData reg for dataIn
  stimuli_dataIn_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF reset = '1' THEN
        holdData_dataIn <= (OTHERS => 'X');
      ELSE
        holdData_dataIn <= rawData_dataIn;
      END IF;
    END IF;
  END PROCESS stimuli_dataIn_process;

  stimuli_dataIn_1: PROCESS (rawData_dataIn, rdEnb)
  BEGIN
    IF rdEnb = '0' THEN
      dataIn_offset <= holdData_dataIn;
    ELSE
      dataIn_offset <= rawData_dataIn;
    END IF;
  END PROCESS stimuli_dataIn_1;

  dataIn_1 <= dataIn_offset AFTER 2 ns;

  dataIn_2 <= std_logic_vector(dataIn_1);

  snkDonen <=  NOT snkDone;

  resetn <=  NOT reset;

  tb_enb <= resetn AND snkDonen;

  
  rdEnb <= tb_enb WHEN snkDone = '0' ELSE
      '0';

  enb <= rdEnb AFTER 2 ns;

  reset_gen: PROCESS 
  BEGIN
    reset <= '1';
    WAIT FOR 20 ns;
    WAIT UNTIL clk'event AND clk = '1';
    WAIT FOR 2 ns;
    reset <= '0';
    WAIT;
  END PROCESS reset_gen;

  clk_gen: PROCESS 
  BEGIN
    clk <= '1';
    WAIT FOR 5 ns;
    clk <= '0';
    WAIT FOR 5 ns;
    IF snkDone = '1' THEN
      clk <= '1';
      WAIT FOR 5 ns;
      clk <= '0';
      WAIT FOR 5 ns;
      WAIT;
    END IF;
  END PROCESS clk_gen;

  dataOut_enb <= ce_out AND dataOut_active;

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 1023
  dataOut_1_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        dataOut_addr <= to_unsigned(16#000#, 10);
      ELSIF dataOut_enb = '1' THEN
        dataOut_addr <= dataOut_addr + to_unsigned(16#001#, 10);
      END IF;
    END IF;
  END PROCESS dataOut_1_process;


  
  dataOut_lastAddr <= '1' WHEN dataOut_addr = to_unsigned(16#3FF#, 10) ELSE
      '0';

  dataOut_done <= dataOut_lastAddr AND resetn;

  -- Delay to allow last sim cycle to complete
  checkDone_1_process: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF reset = '1' THEN
        check1_done <= '0';
      ELSIF dataOut_done_enb = '1' THEN
        check1_done <= dataOut_done;
      END IF;
    END IF;
  END PROCESS checkDone_1_process;

  snkDone <= check1_done AND check2_done;

  dataOut_signed <= signed(dataOut);

  dataOut_addr_delay_1 <= dataOut_addr AFTER 1 ns;

  -- Data source for dataOut_expected
  dataOut_expected_fileread: PROCESS (dataOut_addr_delay_1, tb_enb, ce_out)
    FILE fp: TEXT open READ_MODE is "dataOut_expected.dat";
    VARIABLE l: LINE;
    VARIABLE read_data: std_logic_vector(15 DOWNTO 0);

  BEGIN
    IF tb_enb /= '1' THEN
    ELSIF ce_out = '1' AND NOT ENDFILE(fp) THEN
      READLINE(fp, l);
      HREAD(l, read_data);
    END IF;
    dataOut_expected <= signed(read_data(15 DOWNTO 0));
  END PROCESS dataOut_expected_fileread;

  dataOut_ref <= dataOut_expected;

  dataOut_signed_checker: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dataOut_testFailure <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' AND dataOut_signed /= dataOut_ref THEN
        dataOut_testFailure <= '1';
        ASSERT FALSE
          REPORT "Error in dataOut_signed: Expected " & to_hex(dataOut_ref) & (" Actual " & to_hex(dataOut_signed))
          SEVERITY ERROR;
      END IF;
    END IF;
  END PROCESS dataOut_signed_checker;

  validOut_addr_delay_1 <= dataOut_addr AFTER 1 ns;

  -- Data source for validOut_expected
  validOut_expected_fileread: PROCESS (validOut_addr_delay_1, tb_enb, ce_out)
    FILE fp: TEXT open READ_MODE is "validOut_expected.dat";
    VARIABLE l: LINE;
    VARIABLE read_data: std_logic;

  BEGIN
    IF tb_enb /= '1' THEN
    ELSIF ce_out = '1' AND NOT ENDFILE(fp) THEN
      READLINE(fp, l);
      READ(l, read_data);
    END IF;
    validOut_expected <= read_data;
  END PROCESS validOut_expected_fileread;

  validOut_ref <= validOut_expected;

  validOut_checker: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      validOut_testFailure <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' AND validOut /= validOut_ref THEN
        validOut_testFailure <= '1';
        ASSERT FALSE
          REPORT "Error in validOut: Expected " & to_hex(validOut_ref) & (" Actual " & to_hex(validOut))
          SEVERITY ERROR;
      END IF;
    END IF;
  END PROCESS validOut_checker;

  testFailure <= dataOut_testFailure OR validOut_testFailure;

  completed_msg: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF snkDone = '1' THEN
        IF testFailure = '0' THEN
          ASSERT FALSE
            REPORT "**************TEST COMPLETED (PASSED)**************"
            SEVERITY NOTE;
        ELSE
          ASSERT FALSE
            REPORT "**************TEST COMPLETED (FAILED)**************"
            SEVERITY NOTE;
        END IF;
      END IF;
    END IF;
  END PROCESS completed_msg;

END rtl;

