-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\gm_Moving_Average_sim\Gain_unaryminus.vhd
-- Created: 2025-09-08 20:52:44
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Gain_unaryminus
-- Source Path: gm_Moving_Average_sim/Moving Average/Gain_unaryminus
-- Hierarchy Level: 1
-- Model version: 1.2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Gain_unaryminus IS
  PORT( In1                               :   IN    std_logic_vector(63 DOWNTO 0);  -- double
        Out1                              :   OUT   std_logic_vector(63 DOWNTO 0)  -- double
        );
END Gain_unaryminus;


ARCHITECTURE rtl OF Gain_unaryminus IS

  -- Component Declarations
  COMPONENT nfp_uminus_double
    PORT( nfp_in                          :   IN    std_logic_vector(63 DOWNTO 0);  -- double
          nfp_out                         :   OUT   std_logic_vector(63 DOWNTO 0)  -- double
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : nfp_uminus_double
    USE ENTITY work.nfp_uminus_double(rtl);

  -- Signals
  SIGNAL Gain_unaryminus_out1             : std_logic_vector(63 DOWNTO 0);  -- ufix64

BEGIN
  u_nfp_uminus_comp : nfp_uminus_double
    PORT MAP( nfp_in => In1,  -- double
              nfp_out => Gain_unaryminus_out1  -- double
              );

  Out1 <= Gain_unaryminus_out1;

END rtl;

