-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\gm_Moving_Average_sim\Gain1.vhd
-- Created: 2025-09-08 20:52:44
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Gain1
-- Source Path: gm_Moving_Average_sim/Moving Average/Gain1
-- Hierarchy Level: 1
-- Model version: 1.2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Gain1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        In1                               :   IN    std_logic_vector(63 DOWNTO 0);  -- double
        Out1                              :   OUT   std_logic_vector(63 DOWNTO 0)  -- double
        );
END Gain1;


ARCHITECTURE rtl OF Gain1 IS

  -- Component Declarations
  COMPONENT nfp_gain_pow2_double
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          nfp_in1                         :   IN    std_logic_vector(63 DOWNTO 0);  -- double
          nfp_in2                         :   IN    std_logic;  -- ufix1
          nfp_in3                         :   IN    std_logic_vector(11 DOWNTO 0);  -- sfix12
          nfp_out                         :   OUT   std_logic_vector(63 DOWNTO 0)  -- double
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : nfp_gain_pow2_double
    USE ENTITY work.nfp_gain_pow2_double(rtl);

  -- Signals
  SIGNAL pw2_sign_const                   : std_logic;  -- ufix1
  SIGNAL pw2_shift_const                  : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Gain1_out1                       : std_logic_vector(63 DOWNTO 0);  -- ufix64

BEGIN
  u_nfp_gain_pow2_double : nfp_gain_pow2_double
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              nfp_in1 => In1,  -- double
              nfp_in2 => pw2_sign_const,  -- ufix1
              nfp_in3 => std_logic_vector(pw2_shift_const),  -- sfix12
              nfp_out => Gain1_out1  -- double
              );

  pw2_sign_const <= '0';

  pw2_shift_const <= to_signed(16#002#, 12);

  Out1 <= Gain1_out1;

END rtl;

