-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\gm_Moving_Average_sim\Moving_Average_tb.vhd
-- Created: 2025-09-08 20:53:42
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.0001
-- Target subsystem base rate: 0.0001
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Moving_Average_tb
-- Source Path: 
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_textio.ALL;
USE IEEE.float_pkg.ALL;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
LIBRARY STD;
USE STD.textio.ALL;
LIBRARY work;
USE work.Moving_Average_pkg.ALL;
USE work.Moving_Average_tb_pkg.ALL;

ENTITY Moving_Average_tb IS
END Moving_Average_tb;


ARCHITECTURE rtl OF Moving_Average_tb IS

  -- Component Declarations
  COMPONENT Moving_Average
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          Input                           :   IN    std_logic_vector(63 DOWNTO 0);  -- double
          ce_out                          :   OUT   std_logic;
          Output                          :   OUT   std_logic_vector(63 DOWNTO 0)  -- double
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Moving_Average
    USE ENTITY work.Moving_Average(rtl);

  -- Signals
  SIGNAL clk                              : std_logic;
  SIGNAL reset                            : std_logic;
  SIGNAL clk_enable                       : std_logic;
  SIGNAL Output_done                      : std_logic;  -- ufix1
  SIGNAL rdEnb                            : std_logic;
  SIGNAL Output_done_enb                  : std_logic;  -- ufix1
  SIGNAL Output_addr                      : unsigned(17 DOWNTO 0);  -- ufix18
  SIGNAL Output_active                    : std_logic;  -- ufix1
  SIGNAL Repeating_Sequence_Stair_out1_addr : unsigned(17 DOWNTO 0);  -- ufix18
  SIGNAL Repeating_Sequence_Stair_out1_active : std_logic;  -- ufix1
  SIGNAL tb_enb_delay                     : std_logic;
  SIGNAL Repeating_Sequence_Stair_out1_enb : std_logic;  -- ufix1
  SIGNAL Repeating_Sequence_Stair_out1_addr_delay_1 : unsigned(17 DOWNTO 0);  -- ufix18
  SIGNAL tb_enb                           : std_logic;
  SIGNAL rawData_Input                    : std_logic_vector(63 DOWNTO 0);  -- ufix64
  SIGNAL holdData_Input                   : std_logic_vector(63 DOWNTO 0);  -- ufix64
  SIGNAL Input_offset                     : std_logic_vector(63 DOWNTO 0);  -- ufix64
  SIGNAL Input                            : std_logic_vector(63 DOWNTO 0);  -- ufix64
  SIGNAL snkDone                          : std_logic;
  SIGNAL snkDonen                         : std_logic;
  SIGNAL resetn                           : std_logic;
  SIGNAL ce_out                           : std_logic;
  SIGNAL Output                           : std_logic_vector(63 DOWNTO 0);  -- ufix64
  SIGNAL Output_enb                       : std_logic;  -- ufix1
  SIGNAL Output_lastAddr                  : std_logic;  -- ufix1
  SIGNAL Output_addr_delay_1              : unsigned(17 DOWNTO 0);  -- ufix18
  SIGNAL Output_expected                  : std_logic_vector(63 DOWNTO 0);  -- ufix64
  SIGNAL Output_ref                       : std_logic_vector(63 DOWNTO 0);  -- ufix64
  SIGNAL Output_testFailure               : std_logic;  -- ufix1

BEGIN
  u_Moving_Average : Moving_Average
    PORT MAP( clk => clk,
              reset => reset,
              clk_enable => clk_enable,
              Input => Input,  -- double
              ce_out => ce_out,
              Output => Output  -- double
              );

  Output_done_enb <= Output_done AND rdEnb;

  
  Output_active <= '1' WHEN Output_addr /= to_unsigned(16#30D40#, 18) ELSE
      '0';

  
  Repeating_Sequence_Stair_out1_active <= '1' WHEN Repeating_Sequence_Stair_out1_addr /= to_unsigned(16#30D40#, 18) ELSE
      '0';

  Repeating_Sequence_Stair_out1_enb <= Repeating_Sequence_Stair_out1_active AND (rdEnb AND tb_enb_delay);

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 200000
  RepeatingSequenceStair_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Repeating_Sequence_Stair_out1_addr <= to_unsigned(16#00000#, 18);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF Repeating_Sequence_Stair_out1_enb = '1' THEN
        IF Repeating_Sequence_Stair_out1_addr >= to_unsigned(16#30D40#, 18) THEN 
          Repeating_Sequence_Stair_out1_addr <= to_unsigned(16#00000#, 18);
        ELSE 
          Repeating_Sequence_Stair_out1_addr <= Repeating_Sequence_Stair_out1_addr + to_unsigned(16#00001#, 18);
        END IF;
      END IF;
    END IF;
  END PROCESS RepeatingSequenceStair_process;


  Repeating_Sequence_Stair_out1_addr_delay_1 <= Repeating_Sequence_Stair_out1_addr AFTER 1 ns;

  -- Data source for Input
  Input_fileread: PROCESS (Repeating_Sequence_Stair_out1_addr_delay_1, tb_enb_delay, rdEnb)
    FILE fp: TEXT open READ_MODE is "C:\\Users\\Luiz\\Documents\\GitHub\\Advanced-Digital-System-Development-Using-MATLAB-C-and-VHDL\\1_LINGUAGENS_HDL_E_VHDL\\5_EXEMPLO_MEDIA_MOVEL_HDL_CODER\\MATLAB_CODER\\hdl_prj\\hdlsrc\\gm_Moving_Average_sim\\Input.dat";
    VARIABLE l: LINE;
    VARIABLE read_data: std_logic_vector(63 DOWNTO 0);

  BEGIN
    IF tb_enb_delay /= '1' THEN
    ELSIF rdEnb = '1' AND NOT ENDFILE(fp) THEN
      READLINE(fp, l);
      HREAD(l, read_data);
    END IF;
    rawData_Input <= std_logic_vector(read_data(63 DOWNTO 0));
  END PROCESS Input_fileread;

  -- holdData reg for Repeating_Sequence_Stair_out1
  stimuli_Repeating_Sequence_Stair_out1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      holdData_Input <= (OTHERS => 'X');
    ELSIF clk'event AND clk = '1' THEN
      holdData_Input <= rawData_Input;
    END IF;
  END PROCESS stimuli_Repeating_Sequence_Stair_out1_process;

  stimuli_Repeating_Sequence_Stair_out1_1: PROCESS (rawData_Input, rdEnb)
  BEGIN
    IF rdEnb = '0' THEN
      Input_offset <= holdData_Input;
    ELSE
      Input_offset <= rawData_Input;
    END IF;
  END PROCESS stimuli_Repeating_Sequence_Stair_out1_1;

  Input <= Input_offset AFTER 2 ns;

  snkDonen <=  NOT snkDone;

  resetn <=  NOT reset;

  tb_enb <= resetn AND snkDonen;

  -- Delay inside enable generation: register depth 1
  u_enable_delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tb_enb_delay <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      tb_enb_delay <= tb_enb;
    END IF;
  END PROCESS u_enable_delay_process;


  
  rdEnb <= tb_enb_delay WHEN snkDone = '0' ELSE
      '0';

  clk_enable <= rdEnb AFTER 2 ns;

  reset_gen: PROCESS 
  BEGIN
    reset <= '1';
    WAIT FOR 20 ns;
    WAIT UNTIL clk'event AND clk = '1';
    WAIT FOR 2 ns;
    reset <= '0';
    WAIT;
  END PROCESS reset_gen;

  clk_gen: PROCESS 
  BEGIN
    clk <= '1';
    WAIT FOR 5 ns;
    clk <= '0';
    WAIT FOR 5 ns;
    IF snkDone = '1' THEN
      clk <= '1';
      WAIT FOR 5 ns;
      clk <= '0';
      WAIT FOR 5 ns;
      WAIT;
    END IF;
  END PROCESS clk_gen;

  Output_enb <= ce_out AND Output_active;

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 200000
  c_4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Output_addr <= to_unsigned(16#00000#, 18);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF Output_enb = '1' THEN
        IF Output_addr >= to_unsigned(16#30D40#, 18) THEN 
          Output_addr <= to_unsigned(16#00000#, 18);
        ELSE 
          Output_addr <= Output_addr + to_unsigned(16#00001#, 18);
        END IF;
      END IF;
    END IF;
  END PROCESS c_4_process;


  
  Output_lastAddr <= '1' WHEN Output_addr >= to_unsigned(16#30D40#, 18) ELSE
      '0';

  Output_done <= Output_lastAddr AND resetn;

  -- Delay to allow last sim cycle to complete
  checkDone_1_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      snkDone <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF Output_done_enb = '1' THEN
        snkDone <= Output_done;
      END IF;
    END IF;
  END PROCESS checkDone_1_process;

  Output_addr_delay_1 <= Output_addr AFTER 1 ns;

  -- Data source for Output_expected
  Output_expected_fileread: PROCESS (Output_addr_delay_1, tb_enb_delay, ce_out)
    FILE fp: TEXT open READ_MODE is "C:\\Users\\Luiz\\Documents\\GitHub\\Advanced-Digital-System-Development-Using-MATLAB-C-and-VHDL\\1_LINGUAGENS_HDL_E_VHDL\\5_EXEMPLO_MEDIA_MOVEL_HDL_CODER\\MATLAB_CODER\\hdl_prj\\hdlsrc\\gm_Moving_Average_sim\\Output_expected.dat";
    VARIABLE l: LINE;
    VARIABLE read_data: std_logic_vector(63 DOWNTO 0);

  BEGIN
    IF tb_enb_delay /= '1' THEN
    ELSIF ce_out = '1' AND NOT ENDFILE(fp) THEN
      READLINE(fp, l);
      HREAD(l, read_data);
    END IF;
    Output_expected <= std_logic_vector(read_data(63 DOWNTO 0));
  END PROCESS Output_expected_fileread;

  Output_ref <= Output_expected;

  Output_checker: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Output_testFailure <= '0';
    ELSIF clk'event AND clk = '1' THEN
      IF ce_out = '1' AND NOT isFloatDoubleEqual(Output, Output_ref, 9.9999999999999995e-08) THEN
        Output_testFailure <= '1';
        ASSERT FALSE
          REPORT "Error in Output: Expected " & to_hex(Output_ref) & (" Actual " & to_hex(Output))
          SEVERITY ERROR;
      END IF;
    END IF;
  END PROCESS Output_checker;

  completed_msg: PROCESS (clk)
  BEGIN
    IF clk'event AND clk = '1' THEN
      IF snkDone = '1' THEN
        IF Output_testFailure = '0' THEN
          ASSERT FALSE
            REPORT "**************TEST COMPLETED (PASSED)**************"
            SEVERITY NOTE;
        ELSE
          ASSERT FALSE
            REPORT "**************TEST COMPLETED (FAILED)**************"
            SEVERITY NOTE;
        END IF;
      END IF;
    END IF;
  END PROCESS completed_msg;

END rtl;

