-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\gm_Moving_Average_sim\Rate_Transition.vhd
-- Created: 2025-09-08 20:52:44
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Rate_Transition
-- Source Path: gm_Moving_Average_sim/Moving Average/Rate Transition
-- Hierarchy Level: 1
-- Model version: 1.2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Rate_Transition IS
  PORT( in_rsvd                           :   IN    std_logic_vector(63 DOWNTO 0);  -- double
        out_rsvd                          :   OUT   std_logic_vector(63 DOWNTO 0)  -- double
        );
END Rate_Transition;


ARCHITECTURE rtl OF Rate_Transition IS

BEGIN
  out_rsvd <= in_rsvd;

END rtl;

