-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\gm_Moving_Average_sim\Sum1.vhd
-- Created: 2025-09-08 20:52:44
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Sum1
-- Source Path: gm_Moving_Average_sim/Moving Average/Sum1
-- Hierarchy Level: 1
-- Model version: 1.2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Sum1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        In1                               :   IN    std_logic_vector(63 DOWNTO 0);  -- double
        In2                               :   IN    std_logic_vector(63 DOWNTO 0);  -- double
        Out1                              :   OUT   std_logic_vector(63 DOWNTO 0)  -- double
        );
END Sum1;


ARCHITECTURE rtl OF Sum1 IS

  -- Component Declarations
  COMPONENT nfp_add_double
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          nfp_in1                         :   IN    std_logic_vector(63 DOWNTO 0);  -- double
          nfp_in2                         :   IN    std_logic_vector(63 DOWNTO 0);  -- double
          nfp_out                         :   OUT   std_logic_vector(63 DOWNTO 0)  -- double
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : nfp_add_double
    USE ENTITY work.nfp_add_double(rtl);

  -- Signals
  SIGNAL Sum1_out1                        : std_logic_vector(63 DOWNTO 0);  -- ufix64

BEGIN
  u_nfp_add_comp : nfp_add_double
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              nfp_in1 => In1,  -- double
              nfp_in2 => In2,  -- double
              nfp_out => Sum1_out1  -- double
              );

  Out1 <= Sum1_out1;

END rtl;

