function [dataOut,validOut] = hdl_IP(dataIn,validIn)
% Generated by HDL IP Designer.

persistent ipblock

if isempty(ipblock)
    ipblock = dsphdl.FIRFilter(...
        'Numerator',[0.154923537307848 0.168872827249808 0.176203635442344 0.176203635442344 0.168872827249808 0.154923537307848]);
end

[dataOut,validOut] = ipblock(dataIn,validIn);

end
