#ifndef PORTABLE_WORDSIZES
#ifdef __MW_TARGET_USE_HARDWARE_RESOURCES_H__
#ifndef __MW_TARGET_HARDWARE_RESOURCES_H__
#define __MW_TARGET_HARDWARE_RESOURCES_H__

#define MW_MULTI_TASKING_MODE 1

#define MW_USECODERTARGET 1
#define MW_TARGETHARDWARE Altera Cyclone V SoC development kit
#define MW_ESB_PROCESSINGUNIT APU
#define MW_ESB_SIMDIAGSHOWINSDI 1
#define MW_ESB_SIMDIAGSAVETOFILE 1
#define MW_ESB_SIMDIAGOVERWRITEFILE 0
#define MW_ESB_HWDIAGSHOWINSDI 0
#define MW_ESB_HWDIAGSAVETOFILE 0
#define MW_ESB_HWDIAGOVERWRITEFILE 0
#define MW_ESB_HWDIAGINSTRUMENTATION Code
#define MW_ESB_HWDIAGRECORDING Continuous
#define MW_ESB_HWDIAGSTREAMINGMODETYPE Unlimited
#define MW_ESB_HWDIAGBUFFERSIZE 1024.000000
#define MW_ESB_HWDIAGNUMBUFFERS 1.000000
#define MW_ESB_HWDIAGVIEWLEVEL Task manager tasks
#define MW_ESB_SETRNG 0
#define MW_ESB_RNGSEED default
#define MW_ESB_CACHEDATA 0
#define MW_ESB_SCHEDULEEDITORSCHEDULERESET 0
#define MW_DATAVERSION 2016.02
#define MW_CONNECTIONINFO_TCPIP_IPADDRESS codertarget.alterasoc.HardwareParameterInfo.getDeviceAddress
#define MW_CONNECTIONINFO_TCPIP_PORT 17725
#define MW_CONNECTIONINFO_TCPIP_VERBOSE 0
#define MW_CONNECTIONINFO_TCPIP_RUNINBACKGROUND 1
#define MW_CONNECTIONINFO_XCPONTCPIP_IPADDRESS codertarget.alterasoc.HardwareParameterInfo.getDeviceAddress
#define MW_CONNECTIONINFO_XCPONTCPIP_PORT 17725
#define MW_CONNECTIONINFO_XCPONTCPIP_VERBOSE 0
#define MW_EXTMODE_CONFIGURATION TCP/IP
#define MW_TARGETSERVICES_RUNNING 0
#define MW_FPGADESIGN_INCLUDEAXIINTERCONNECTMONITOR 0.000000
#define MW_FPGADESIGN_NUMBEROFTRACEEVENTS 1024.000000
#define MW_FPGADESIGN_PROJECTFOLDER soc_prj
#define MW_FPGADESIGN_MEMCHDIAGLEVEL No debug
#define MW_RTOS Linux
#define MW_RTOSBASERATETASKPRIORITY 40
#define MW_DETECTTASKOVERRUNS 0.000000
#define MW_SCHEDULER_INTERRUPT_SOURCE 0
#define MW_BOARDPARAMETERS_DEVICEADDRESS 192.168.1.100
#define MW_BOARDPARAMETERS_USERNAME root
#define MW_BOARDPARAMETERS_PASSWORD cyclonevsoc
#define MW_RUNTIME_BUILDACTION 0
#define MW_CLOCKING_CPUCLOCKRATEMHZ 1000

#endif /* __MW_TARGET_HARDWARE_RESOURCES_H__ */

#endif

#endif
