open_system('iir_filter_simulink');
open_system('gm_iir_filter_simulink');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_filter_simulink/Filter1/a2_sec1', 'user2');
hilite_system('iir_filter_simulink/Filter1', 'user2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_filter_simulink/Filter1/sum_a2_sec1', 'user2');
hilite_system('iir_filter_simulink/Filter1', 'user2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_filter_simulink/Filter1/sum_a1_sec1', 'user2');
hilite_system('iir_filter_simulink/Filter1', 'user2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_filter_simulink/Filter1/input_delay2_sec1_absorbed', 'user2');
hilite_system('iir_filter_simulink/Filter1', 'user2');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_iir_filter_simulink/Filter1/input_delay1_sec1_absorbed', 'user2');
hilite_system('iir_filter_simulink/Filter1', 'user2');
