-- -------------------------------------------------------------
-- 
-- File Name: C:\curso_HDL_Vanderlei\Advanced-Digital-System-Development-Using-MATLAB-C-and-VHDL\1_LINGUAGENS_HDL_E_VHDL\6_EXEMPLO_FILTRO_FIR_HDL_CODER\hdlsrc\filter_low_pass_simulink\filter_lo_ip_dut.vhd
-- Created: 2025-09-15 17:09:16
-- 
-- Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: filter_lo_ip_dut
-- Source Path: filter_lo_ip/filter_lo_ip_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY filter_lo_ip_dut IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        dut_enable                        :   IN    std_logic;  -- ufix1
        In1                               :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        ce_out                            :   OUT   std_logic;  -- ufix1
        Out1                              :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
        );
END filter_lo_ip_dut;


ARCHITECTURE rtl OF filter_lo_ip_dut IS

  -- Component Declarations
  COMPONENT filter_lo_ip_src_filter_low_pass_simulink
    PORT( clk                             :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          reset                           :   IN    std_logic;
          In1                             :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          ce_out                          :   OUT   std_logic;  -- ufix1
          Out1                            :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : filter_lo_ip_src_filter_low_pass_simulink
    USE ENTITY work.filter_lo_ip_src_filter_low_pass_simulink(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL Out1_sig                         : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_filter_lo_ip_src_filter_low_pass_simulink : filter_lo_ip_src_filter_low_pass_simulink
    PORT MAP( clk => clk,
              clk_enable => enb,
              reset => reset,
              In1 => In1,  -- ufix32
              ce_out => ce_out_sig,  -- ufix1
              Out1 => Out1_sig  -- ufix32
              );

  enb <= dut_enable;

  ce_out <= ce_out_sig;

  Out1 <= Out1_sig;

END rtl;

